# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_preferences.ui'
#
# Created: Sun Aug 11 00:00:28 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(850, 670)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ide-icons/rc/Preferences-system.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lwMenu = QtGui.QListWidget(Dialog)
        self.lwMenu.setMaximumSize(QtCore.QSize(72, 16777215))
        self.lwMenu.setIconSize(QtCore.QSize(64, 64))
        self.lwMenu.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.lwMenu.setViewMode(QtGui.QListView.IconMode)
        self.lwMenu.setObjectName(_fromUtf8("lwMenu"))
        item = QtGui.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/ide-icons/rc/Preferences-system-64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.lwMenu.addItem(item)
        item = QtGui.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/ide-icons/rc/Mypaint-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.lwMenu.addItem(item)
        self.gridLayout.addWidget(self.lwMenu, 0, 0, 1, 1)
        self.swMain = QtGui.QStackedWidget(Dialog)
        self.swMain.setObjectName(_fromUtf8("swMain"))
        self.pGeneral = QtGui.QWidget()
        self.pGeneral.setObjectName(_fromUtf8("pGeneral"))
        self.formLayout = QtGui.QFormLayout(self.pGeneral)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.cbCodeCompletion = QtGui.QCheckBox(self.pGeneral)
        self.cbCodeCompletion.setChecked(True)
        self.cbCodeCompletion.setObjectName(_fromUtf8("cbCodeCompletion"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.cbCodeCompletion)
        self.cbUseExtShell = QtGui.QCheckBox(self.pGeneral)
        self.cbUseExtShell.setObjectName(_fromUtf8("cbUseExtShell"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.cbUseExtShell)
        self.lblExternalTerminal = QtGui.QLabel(self.pGeneral)
        self.lblExternalTerminal.setObjectName(_fromUtf8("lblExternalTerminal"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblExternalTerminal)
        self.leTerminal = QtGui.QLineEdit(self.pGeneral)
        self.leTerminal.setObjectName(_fromUtf8("leTerminal"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.leTerminal)
        self.swMain.addWidget(self.pGeneral)
        self.pStyle = QtGui.QWidget()
        self.pStyle.setObjectName(_fromUtf8("pStyle"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pStyle)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblFont = QtGui.QLabel(self.pStyle)
        self.lblFont.setObjectName(_fromUtf8("lblFont"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblFont)
        self.lblFontSize = QtGui.QLabel(self.pStyle)
        self.lblFontSize.setObjectName(_fromUtf8("lblFontSize"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFontSize)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sbFontSize = QtGui.QSpinBox(self.pStyle)
        self.sbFontSize.setMinimumSize(QtCore.QSize(50, 0))
        self.sbFontSize.setMinimum(1)
        self.sbFontSize.setProperty("value", 10)
        self.sbFontSize.setObjectName(_fromUtf8("sbFontSize"))
        self.horizontalLayout_3.addWidget(self.sbFontSize)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.lblPygmentStyle = QtGui.QLabel(self.pStyle)
        self.lblPygmentStyle.setObjectName(_fromUtf8("lblPygmentStyle"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblPygmentStyle)
        self.lwColors = QtGui.QListWidget(self.pStyle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwColors.sizePolicy().hasHeightForWidth())
        self.lwColors.setSizePolicy(sizePolicy)
        self.lwColors.setMaximumSize(QtCore.QSize(129, 16777215))
        self.lwColors.setObjectName(_fromUtf8("lwColors"))
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lwColors.addItem(item)
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lwColors)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pbColor = QtGui.QPushButton(self.pStyle)
        self.pbColor.setMinimumSize(QtCore.QSize(50, 0))
        self.pbColor.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.pbColor.setText(_fromUtf8(""))
        self.pbColor.setAutoDefault(True)
        self.pbColor.setFlat(False)
        self.pbColor.setObjectName(_fromUtf8("pbColor"))
        self.horizontalLayout_2.addWidget(self.pbColor)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fcbFont = QtGui.QFontComboBox(self.pStyle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fcbFont.sizePolicy().hasHeightForWidth())
        self.fcbFont.setSizePolicy(sizePolicy)
        self.fcbFont.setMinimumSize(QtCore.QSize(200, 0))
        self.fcbFont.setFontFilters(QtGui.QFontComboBox.MonospacedFonts)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans Mono"))
        font.setPointSize(6)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.fcbFont.setCurrentFont(font)
        self.fcbFont.setObjectName(_fromUtf8("fcbFont"))
        self.horizontalLayout.addWidget(self.fcbFont)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cmbPygmentsStyle = QtGui.QComboBox(self.pStyle)
        self.cmbPygmentsStyle.setMinimumSize(QtCore.QSize(200, 0))
        self.cmbPygmentsStyle.setObjectName(_fromUtf8("cmbPygmentsStyle"))
        self.horizontalLayout_4.addWidget(self.cmbPygmentsStyle)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.cbLineNbr = QtGui.QCheckBox(self.pStyle)
        self.cbLineNbr.setChecked(True)
        self.cbLineNbr.setObjectName(_fromUtf8("cbLineNbr"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.cbLineNbr)
        self.cbWhitespaces = QtGui.QCheckBox(self.pStyle)
        self.cbWhitespaces.setChecked(False)
        self.cbWhitespaces.setObjectName(_fromUtf8("cbWhitespaces"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.cbWhitespaces)
        self.gridLayout_2.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.plainTextEdit = CobolEditor(self.pStyle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_2.addWidget(self.plainTextEdit, 2, 0, 1, 1)
        self.swMain.addWidget(self.pStyle)
        self.gridLayout.addWidget(self.swMain, 0, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.swMain.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Preferences", None))
        __sortingEnabled = self.lwMenu.isSortingEnabled()
        self.lwMenu.setSortingEnabled(False)
        item = self.lwMenu.item(0)
        item.setText(_translate("Dialog", "General", None))
        item.setToolTip(_translate("Dialog", "General", None))
        item = self.lwMenu.item(1)
        item.setText(_translate("Dialog", "Style", None))
        item.setToolTip(_translate("Dialog", " Style", None))
        self.lwMenu.setSortingEnabled(__sortingEnabled)
        self.cbCodeCompletion.setText(_translate("Dialog", "Code completion", None))
        self.cbUseExtShell.setText(_translate("Dialog", "Run program in external terminal", None))
        self.lblExternalTerminal.setText(_translate("Dialog", "External terminal command:", None))
        self.leTerminal.setText(_translate("Dialog", "gnome-terminal -e", None))
        self.lblFont.setText(_translate("Dialog", "Font: ", None))
        self.lblFontSize.setText(_translate("Dialog", "Font size: ", None))
        self.lblPygmentStyle.setText(_translate("Dialog", "Pygments style: ", None))
        __sortingEnabled = self.lwColors.isSortingEnabled()
        self.lwColors.setSortingEnabled(False)
        item = self.lwColors.item(0)
        item.setText(_translate("Dialog", "Margin", None))
        item = self.lwColors.item(1)
        item.setText(_translate("Dialog", "ActiveLine", None))
        item = self.lwColors.item(2)
        item.setText(_translate("Dialog", "Selection", None))
        item = self.lwColors.item(3)
        item.setText(_translate("Dialog", "SelectedText", None))
        item = self.lwColors.item(4)
        item.setText(_translate("Dialog", "LineNumber", None))
        item = self.lwColors.item(5)
        item.setText(_translate("Dialog", "PanelBackground", None))
        item = self.lwColors.item(6)
        item.setText(_translate("Dialog", "PanelBackground2", None))
        item = self.lwColors.item(7)
        item.setText(_translate("Dialog", "TextOccurences", None))
        item = self.lwColors.item(8)
        item.setText(_translate("Dialog", "SearchResults", None))
        item = self.lwColors.item(9)
        item.setText(_translate("Dialog", "Warning", None))
        item = self.lwColors.item(10)
        item.setText(_translate("Dialog", "Error", None))
        self.lwColors.setSortingEnabled(__sortingEnabled)
        self.cbLineNbr.setText(_translate("Dialog", "Show line numbers", None))
        self.cbWhitespaces.setText(_translate("Dialog", "Show whitespaces", None))

from cobcide.editor import CobolEditor
import ide_rc
