# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ide.ui'
#
# Created: Fri Apr 18 23:30:13 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(900, 700)
        MainWindow.setMinimumSize(QtCore.QSize(900, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ide-icons/rc/silex-64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.QHomeWidget = QHomeWidget(self.page)
        self.QHomeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.QHomeWidget.setProperty("icon", icon)
        self.QHomeWidget.setObjectName(_fromUtf8("QHomeWidget"))
        self.gridLayout_6.addWidget(self.QHomeWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidgetEditors = QCodeEditTabWidget(self.page_2)
        self.tabWidgetEditors.setObjectName(_fromUtf8("tabWidgetEditors"))
        self.gridLayout_2.addWidget(self.tabWidgetEditors, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarFile = QtGui.QToolBar(MainWindow)
        self.toolBarFile.setObjectName(_fromUtf8("toolBarFile"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarFile)
        self.toolBarCode = QtGui.QToolBar(MainWindow)
        self.toolBarCode.setObjectName(_fromUtf8("toolBarCode"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarCode)
        self.dockWidgetLogs = QtGui.QDockWidget(MainWindow)
        self.dockWidgetLogs.setObjectName(_fromUtf8("dockWidgetLogs"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidgetLogs = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidgetLogs.setObjectName(_fromUtf8("tabWidgetLogs"))
        self.tabCompiler = QtGui.QWidget()
        self.tabCompiler.setObjectName(_fromUtf8("tabCompiler"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabCompiler)
        self.gridLayout_4.setMargin(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.errorsTable = QErrorsTable(self.tabCompiler)
        self.errorsTable.setMinimumSize(QtCore.QSize(0, 0))
        self.errorsTable.setObjectName(_fromUtf8("errorsTable"))
        self.errorsTable.setColumnCount(5)
        self.errorsTable.setRowCount(0)
        self.gridLayout_4.addWidget(self.errorsTable, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/ide-icons/rc/applications-system.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetLogs.addTab(self.tabCompiler, icon1, _fromUtf8(""))
        self.tabProgramOutput = QtGui.QWidget()
        self.tabProgramOutput.setObjectName(_fromUtf8("tabProgramOutput"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabProgramOutput)
        self.gridLayout_5.setMargin(6)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.consoleOutput = QInteractiveConsole(self.tabProgramOutput)
        self.consoleOutput.setObjectName(_fromUtf8("consoleOutput"))
        self.gridLayout_5.addWidget(self.consoleOutput, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/ide-icons/rc/media-playback-start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetLogs.addTab(self.tabProgramOutput, icon2, _fromUtf8(""))
        self.tabAppLog = QtGui.QWidget()
        self.tabAppLog.setObjectName(_fromUtf8("tabAppLog"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabAppLog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textEditLogs = QtGui.QTextEdit(self.tabAppLog)
        self.textEditLogs.setReadOnly(True)
        self.textEditLogs.setObjectName(_fromUtf8("textEditLogs"))
        self.verticalLayout.addWidget(self.textEditLogs)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/ide-icons/rc/silex-32x32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidgetLogs.addTab(self.tabAppLog, icon3, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidgetLogs, 1, 0, 1, 1)
        self.dockWidgetLogs.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetLogs)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 27))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRecent_files = QtGui.QMenu(self.menuFile)
        self.menuRecent_files.setObjectName(_fromUtf8("menuRecent_files"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.mnuActiveEditor = QtGui.QMenu(self.menuEdit)
        self.mnuActiveEditor.setObjectName(_fromUtf8("mnuActiveEditor"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuToolbars = QtGui.QMenu(self.menuView)
        self.menuToolbars.setObjectName(_fromUtf8("menuToolbars"))
        self.menuDock_panels = QtGui.QMenu(self.menuView)
        self.menuDock_panels.setObjectName(_fromUtf8("menuDock_panels"))
        self.menuApplication_log = QtGui.QMenu(self.menuView)
        self.menuApplication_log.setObjectName(_fromUtf8("menuApplication_log"))
        self.menuCobol = QtGui.QMenu(self.menuBar)
        self.menuCobol.setObjectName(_fromUtf8("menuCobol"))
        self.menuProgramType = QtGui.QMenu(self.menuCobol)
        self.menuProgramType.setObjectName(_fromUtf8("menuProgramType"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menuBar)
        self.dockWidgetNavPanel = QtGui.QDockWidget(MainWindow)
        self.dockWidgetNavPanel.setMinimumSize(QtCore.QSize(300, 121))
        self.dockWidgetNavPanel.setObjectName(_fromUtf8("dockWidgetNavPanel"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_7.setMargin(6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.twNavigation = QtGui.QTreeWidget(self.dockWidgetContents_2)
        self.twNavigation.setObjectName(_fromUtf8("twNavigation"))
        self.twNavigation.headerItem().setText(0, _fromUtf8("1"))
        self.twNavigation.header().setVisible(False)
        self.gridLayout_7.addWidget(self.twNavigation, 0, 0, 1, 1)
        self.dockWidgetNavPanel.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetNavPanel)
        self.dockWidgetOffsets = QtGui.QDockWidget(MainWindow)
        self.dockWidgetOffsets.setMinimumSize(QtCore.QSize(318, 127))
        self.dockWidgetOffsets.setObjectName(_fromUtf8("dockWidgetOffsets"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tableWidgetOffsets = QtGui.QTableWidget(self.dockWidgetContents_3)
        self.tableWidgetOffsets.setMinimumSize(QtCore.QSize(300, 0))
        self.tableWidgetOffsets.setDragDropOverwriteMode(False)
        self.tableWidgetOffsets.setShowGrid(True)
        self.tableWidgetOffsets.setObjectName(_fromUtf8("tableWidgetOffsets"))
        self.tableWidgetOffsets.setColumnCount(4)
        self.tableWidgetOffsets.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetOffsets.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetOffsets.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetOffsets.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetOffsets.setHorizontalHeaderItem(3, item)
        self.tableWidgetOffsets.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidgetOffsets.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetOffsets.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetOffsets.verticalHeader().setVisible(False)
        self.gridLayout_8.addWidget(self.tableWidgetOffsets, 0, 0, 1, 1)
        self.dockWidgetOffsets.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetOffsets)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("window-close"))
        self.actionQuit.setIcon(icon)
        self.actionQuit.setIconVisibleInMenu(True)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCompile = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("exec"))
        self.actionCompile.setIcon(icon)
        self.actionCompile.setIconVisibleInMenu(True)
        self.actionCompile.setObjectName(_fromUtf8("actionCompile"))
        self.actionRun = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.actionRun.setIcon(icon)
        self.actionRun.setIconVisibleInMenu(True)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave.setIcon(icon)
        self.actionSave.setIconVisibleInMenu(True)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save-as"))
        self.actionSaveAs.setIcon(icon)
        self.actionSaveAs.setIconVisibleInMenu(True)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionFullscreen = QtGui.QAction(MainWindow)
        self.actionFullscreen.setCheckable(True)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-fullscreen"))
        self.actionFullscreen.setIcon(icon)
        self.actionFullscreen.setIconVisibleInMenu(True)
        self.actionFullscreen.setObjectName(_fromUtf8("actionFullscreen"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.actionNew.setIcon(icon)
        self.actionNew.setIconVisibleInMenu(True)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.actionOpen.setIcon(icon)
        self.actionOpen.setIconVisibleInMenu(True)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClear = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.actionClear.setIcon(icon)
        self.actionClear.setIconVisibleInMenu(True)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.aShowFilesToolbar = QtGui.QAction(MainWindow)
        self.aShowFilesToolbar.setCheckable(True)
        self.aShowFilesToolbar.setObjectName(_fromUtf8("aShowFilesToolbar"))
        self.aShowCodeToolbar = QtGui.QAction(MainWindow)
        self.aShowCodeToolbar.setCheckable(True)
        self.aShowCodeToolbar.setObjectName(_fromUtf8("aShowCodeToolbar"))
        self.aShowLogsWin = QtGui.QAction(MainWindow)
        self.aShowLogsWin.setCheckable(True)
        self.aShowLogsWin.setObjectName(_fromUtf8("aShowLogsWin"))
        self.aShowNavWin = QtGui.QAction(MainWindow)
        self.aShowNavWin.setCheckable(True)
        self.aShowNavWin.setObjectName(_fromUtf8("aShowNavWin"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("preferences-system"))
        self.actionPreferences.setIcon(icon)
        self.actionPreferences.setIconVisibleInMenu(True)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help"))
        self.actionHelp.setIcon(icon)
        self.actionHelp.setIconVisibleInMenu(True)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionProgram = QtGui.QAction(MainWindow)
        self.actionProgram.setCheckable(True)
        self.actionProgram.setChecked(True)
        self.actionProgram.setObjectName(_fromUtf8("actionProgram"))
        self.actionSubprogram = QtGui.QAction(MainWindow)
        self.actionSubprogram.setCheckable(True)
        self.actionSubprogram.setObjectName(_fromUtf8("actionSubprogram"))
        self.actionDebug = QtGui.QAction(MainWindow)
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.actionInfos = QtGui.QAction(MainWindow)
        self.actionInfos.setObjectName(_fromUtf8("actionInfos"))
        self.actionWarnings = QtGui.QAction(MainWindow)
        self.actionWarnings.setObjectName(_fromUtf8("actionWarnings"))
        self.actionErrors = QtGui.QAction(MainWindow)
        self.actionErrors.setObjectName(_fromUtf8("actionErrors"))
        self.actionDebug_level = QtGui.QAction(MainWindow)
        self.actionDebug_level.setCheckable(True)
        self.actionDebug_level.setObjectName(_fromUtf8("actionDebug_level"))
        self.actionShowAppLog = QtGui.QAction(MainWindow)
        self.actionShowAppLog.setCheckable(True)
        self.actionShowAppLog.setObjectName(_fromUtf8("actionShowAppLog"))
        self.actionClearLog = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/ide-icons/rc/edit-clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearLog.setIcon(icon4)
        self.actionClearLog.setIconVisibleInMenu(True)
        self.actionClearLog.setObjectName(_fromUtf8("actionClearLog"))
        self.toolBarFile.addAction(self.actionNew)
        self.toolBarFile.addAction(self.actionOpen)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionSave)
        self.toolBarFile.addAction(self.actionSaveAs)
        self.toolBarCode.addAction(self.actionCompile)
        self.toolBarCode.addAction(self.actionRun)
        self.menuRecent_files.addSeparator()
        self.menuRecent_files.addAction(self.actionClear)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuRecent_files.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.mnuActiveEditor.addSeparator()
        self.menuEdit.addAction(self.mnuActiveEditor.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuToolbars.addAction(self.aShowFilesToolbar)
        self.menuToolbars.addAction(self.aShowCodeToolbar)
        self.menuDock_panels.addAction(self.aShowLogsWin)
        self.menuDock_panels.addAction(self.aShowNavWin)
        self.menuApplication_log.addAction(self.actionShowAppLog)
        self.menuApplication_log.addAction(self.actionDebug_level)
        self.menuApplication_log.addSeparator()
        self.menuApplication_log.addAction(self.actionClearLog)
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menuView.addAction(self.menuDock_panels.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuApplication_log.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFullscreen)
        self.menuProgramType.addAction(self.actionProgram)
        self.menuProgramType.addAction(self.actionSubprogram)
        self.menuCobol.addAction(self.menuProgramType.menuAction())
        self.menuCobol.addSeparator()
        self.menuCobol.addAction(self.actionCompile)
        self.menuCobol.addAction(self.actionRun)
        self.menu.addAction(self.actionHelp)
        self.menu.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuCobol.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidgetLogs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenCobolIDE", None))
        self.QHomeWidget.setProperty("title", _translate("MainWindow", "Welcome to OpenCobolIDE", None))
        self.toolBarFile.setWindowTitle(_translate("MainWindow", "Toolbar File", None))
        self.toolBarCode.setWindowTitle(_translate("MainWindow", "Toolbar Code", None))
        self.dockWidgetLogs.setWindowTitle(_translate("MainWindow", "Logs", None))
        self.tabWidgetLogs.setTabText(self.tabWidgetLogs.indexOf(self.tabCompiler), _translate("MainWindow", "Compiler", None))
        self.tabWidgetLogs.setTabToolTip(self.tabWidgetLogs.indexOf(self.tabCompiler), _translate("MainWindow", "Show compiler log", None))
        self.tabWidgetLogs.setTabText(self.tabWidgetLogs.indexOf(self.tabProgramOutput), _translate("MainWindow", "Output", None))
        self.tabWidgetLogs.setTabText(self.tabWidgetLogs.indexOf(self.tabAppLog), _translate("MainWindow", "Application log", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuRecent_files.setTitle(_translate("MainWindow", "Recent files", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.mnuActiveEditor.setTitle(_translate("MainWindow", "Active editor", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuToolbars.setTitle(_translate("MainWindow", "Toolbars", None))
        self.menuDock_panels.setTitle(_translate("MainWindow", "Windows", None))
        self.menuApplication_log.setTitle(_translate("MainWindow", "Application log", None))
        self.menuCobol.setTitle(_translate("MainWindow", "Cobol", None))
        self.menuProgramType.setTitle(_translate("MainWindow", "Program type", None))
        self.menu.setTitle(_translate("MainWindow", "?", None))
        self.dockWidgetNavPanel.setWindowTitle(_translate("MainWindow", "Navigation", None))
        self.dockWidgetOffsets.setWindowTitle(_translate("MainWindow", "Offset calculator", None))
        self.tableWidgetOffsets.setSortingEnabled(True)
        item = self.tableWidgetOffsets.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Level", None))
        item = self.tableWidgetOffsets.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableWidgetOffsets.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Offset", None))
        item = self.tableWidgetOffsets.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PIC", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setToolTip(_translate("MainWindow", "Exit application (Ctrl+Q)", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionCompile.setText(_translate("MainWindow", "Compile", None))
        self.actionCompile.setToolTip(_translate("MainWindow", "Compile the current file (F8)", None))
        self.actionCompile.setShortcut(_translate("MainWindow", "F8", None))
        self.actionRun.setText(_translate("MainWindow", "Run", None))
        self.actionRun.setToolTip(_translate("MainWindow", "Run the current file (F5)", None))
        self.actionRun.setShortcut(_translate("MainWindow", "F5", None))
        self.actionAbout.setText(_translate("MainWindow", "About OpenCobolIDE", None))
        self.actionAbout.setToolTip(_translate("MainWindow", "About OpenCobol IDE (F1)", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save current file (Ctrl+S)", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSaveAs.setText(_translate("MainWindow", "Save as", None))
        self.actionSaveAs.setToolTip(_translate("MainWindow", "Save current file as (Ctrl+Shift+S)", None))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionFullscreen.setText(_translate("MainWindow", "Fullscreen", None))
        self.actionFullscreen.setToolTip(_translate("MainWindow", "Toggle fullscreen (F12)", None))
        self.actionFullscreen.setShortcut(_translate("MainWindow", "F11", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionNew.setToolTip(_translate("MainWindow", "New file (Ctrl+N)", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open a file (Ctrl+O)", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionClear.setText(_translate("MainWindow", "Clear list", None))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear list of recent files", None))
        self.aShowFilesToolbar.setText(_translate("MainWindow", "Files", None))
        self.aShowFilesToolbar.setToolTip(_translate("MainWindow", "Show/Hide the files toolbar", None))
        self.aShowCodeToolbar.setText(_translate("MainWindow", "Code", None))
        self.aShowCodeToolbar.setToolTip(_translate("MainWindow", "Show/Hide code toolbar", None))
        self.aShowLogsWin.setText(_translate("MainWindow", "Logs", None))
        self.aShowLogsWin.setToolTip(_translate("MainWindow", "Show/Hide logs window", None))
        self.aShowLogsWin.setShortcut(_translate("MainWindow", "F9", None))
        self.aShowNavWin.setText(_translate("MainWindow", "Navigation", None))
        self.aShowNavWin.setToolTip(_translate("MainWindow", "Show/Hide navigation panel", None))
        self.aShowNavWin.setShortcut(_translate("MainWindow", "F10", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionPreferences.setToolTip(_translate("MainWindow", "Edit the application settings", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1", None))
        self.actionProgram.setText(_translate("MainWindow", "Executable", None))
        self.actionSubprogram.setText(_translate("MainWindow", "Module", None))
        self.actionDebug.setText(_translate("MainWindow", "Debug", None))
        self.actionInfos.setText(_translate("MainWindow", "Infos", None))
        self.actionWarnings.setText(_translate("MainWindow", "Warnings", None))
        self.actionErrors.setText(_translate("MainWindow", "Errors", None))
        self.actionDebug_level.setText(_translate("MainWindow", "Debug Log Level", None))
        self.actionDebug_level.setToolTip(_translate("MainWindow", "Activate debug messages", None))
        self.actionShowAppLog.setText(_translate("MainWindow", "Show window", None))
        self.actionShowAppLog.setToolTip(_translate("MainWindow", "Show/hide application log window", None))
        self.actionClearLog.setText(_translate("MainWindow", "Clear", None))

from pyqode.widgets import QErrorsTable, QInteractiveConsole, QCodeEditTabWidget, QHomeWidget
from . import ide_rc