# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_preferences.ui'
#
# Created: Sun May 25 17:53:06 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from pyqode.qt import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 594)
        icon = QtGui.QIcon.fromTheme("preferences-system")
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lwMenu = QtWidgets.QListWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwMenu.sizePolicy().hasHeightForWidth())
        self.lwMenu.setSizePolicy(sizePolicy)
        self.lwMenu.setMaximumSize(QtCore.QSize(86, 16777215))
        self.lwMenu.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.lwMenu.setIconSize(QtCore.QSize(64, 64))
        self.lwMenu.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.lwMenu.setMovement(QtWidgets.QListView.Static)
        self.lwMenu.setFlow(QtWidgets.QListView.TopToBottom)
        self.lwMenu.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.lwMenu.setViewMode(QtWidgets.QListView.IconMode)
        self.lwMenu.setUniformItemSizes(True)
        self.lwMenu.setObjectName("lwMenu")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ide-icons/rc/Preferences-system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.lwMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ide-icons/rc/applications-graphics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.lwMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ide-icons/rc/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.lwMenu.addItem(item)
        self.horizontalLayout_2.addWidget(self.lwMenu)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageSettings = QtWidgets.QWidget()
        self.pageSettings.setObjectName("pageSettings")
        self.gridLayout = QtWidgets.QGridLayout(self.pageSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidgetSettings = QtWidgets.QTabWidget(self.pageSettings)
        self.tabWidgetSettings.setObjectName("tabWidgetSettings")
        self.tabEditorsettings = QtWidgets.QWidget()
        self.tabEditorsettings.setObjectName("tabEditorsettings")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabEditorsettings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.propGridSettings = QPropertyGrid(self.tabEditorsettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propGridSettings.sizePolicy().hasHeightForWidth())
        self.propGridSettings.setSizePolicy(sizePolicy)
        self.propGridSettings.setObjectName("propGridSettings")
        self.gridLayout_2.addWidget(self.propGridSettings, 1, 0, 1, 1)
        self.tabWidgetSettings.addTab(self.tabEditorsettings, "")
        self.gridLayout.addWidget(self.tabWidgetSettings, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageSettings)
        self.pageStyle = QtWidgets.QWidget()
        self.pageStyle.setObjectName("pageStyle")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pageStyle)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidgetStyle = QtWidgets.QTabWidget(self.pageStyle)
        self.tabWidgetStyle.setObjectName("tabWidgetStyle")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.rbLightStyle = QtWidgets.QRadioButton(self.tab)
        self.rbLightStyle.setChecked(True)
        self.rbLightStyle.setObjectName("rbLightStyle")
        self.horizontalLayout_3.addWidget(self.rbLightStyle)
        self.rbDarkStyle = QtWidgets.QRadioButton(self.tab)
        self.rbDarkStyle.setObjectName("rbDarkStyle")
        self.horizontalLayout_3.addWidget(self.rbDarkStyle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.propGridStyle = QPropertyGrid(self.tab)
        self.propGridStyle.setObjectName("propGridStyle")
        self.verticalLayout_2.addWidget(self.propGridStyle)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.codeEdit = QCobolCodeEdit(self.tab)
        self.codeEdit.setObjectName("codeEdit")
        self.verticalLayout_2.addWidget(self.codeEdit)
        self.tabWidgetStyle.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.colorButtonConsoleBck = QColorButton(self.tab_2)
        self.colorButtonConsoleBck.setProperty("color", QtGui.QColor(255, 255, 255))
        self.colorButtonConsoleBck.setObjectName("colorButtonConsoleBck")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.colorButtonConsoleBck)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.colorButtonConsoleFore = QColorButton(self.tab_2)
        self.colorButtonConsoleFore.setProperty("color", QtGui.QColor(64, 64, 64))
        self.colorButtonConsoleFore.setObjectName("colorButtonConsoleFore")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.colorButtonConsoleFore)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.colorButtonConsoleApp = QColorButton(self.tab_2)
        self.colorButtonConsoleApp.setProperty("color", QtGui.QColor(64, 64, 255))
        self.colorButtonConsoleApp.setObjectName("colorButtonConsoleApp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.colorButtonConsoleApp)
        self.colorButtonConsoleUsr = QColorButton(self.tab_2)
        self.colorButtonConsoleUsr.setProperty("color", QtGui.QColor(34, 170, 34))
        self.colorButtonConsoleUsr.setObjectName("colorButtonConsoleUsr")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.colorButtonConsoleUsr)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.console = QInteractiveConsole(self.tab_2)
        self.console.setObjectName("console")
        self.verticalLayout_3.addWidget(self.console)
        self.tabWidgetStyle.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.radioButtonWhite = QtWidgets.QRadioButton(self.tab_3)
        self.radioButtonWhite.setChecked(True)
        self.radioButtonWhite.setObjectName("radioButtonWhite")
        self.horizontalLayout.addWidget(self.radioButtonWhite)
        self.radioButtonDark = QtWidgets.QRadioButton(self.tab_3)
        self.radioButtonDark.setObjectName("radioButtonDark")
        self.horizontalLayout.addWidget(self.radioButtonDark)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.homeWidget = QHomeWidget(self.tab_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ide-icons/rc/silex-64x64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeWidget.setProperty("icon", icon3)
        self.homeWidget.setObjectName("homeWidget")
        self.verticalLayout_4.addWidget(self.homeWidget)
        self.tabWidgetStyle.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.tabWidgetStyle, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageStyle)
        self.pageBuildAndRun = QtWidgets.QWidget()
        self.pageBuildAndRun.setObjectName("pageBuildAndRun")
        self.formLayout_2 = QtWidgets.QFormLayout(self.pageBuildAndRun)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.pageBuildAndRun)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.checkBoxExtTerm = QtWidgets.QCheckBox(self.pageBuildAndRun)
        self.checkBoxExtTerm.setText("")
        self.checkBoxExtTerm.setObjectName("checkBoxExtTerm")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxExtTerm)
        self.labelShellCmd = QtWidgets.QLabel(self.pageBuildAndRun)
        self.labelShellCmd.setObjectName("labelShellCmd")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelShellCmd)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditShellCmd = QtWidgets.QLineEdit(self.pageBuildAndRun)
        self.lineEditShellCmd.setObjectName("lineEditShellCmd")
        self.horizontalLayout_5.addWidget(self.lineEditShellCmd)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.pageBuildAndRun)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidgetSettings.setCurrentIndex(0)
        self.tabWidgetStyle.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lwMenu, self.tabWidgetStyle)
        Dialog.setTabOrder(self.tabWidgetStyle, self.codeEdit)
        Dialog.setTabOrder(self.codeEdit, self.console)
        Dialog.setTabOrder(self.console, self.radioButtonWhite)
        Dialog.setTabOrder(self.radioButtonWhite, self.radioButtonDark)
        Dialog.setTabOrder(self.radioButtonDark, self.tabWidgetSettings)
        Dialog.setTabOrder(self.tabWidgetSettings, self.buttonBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        __sortingEnabled = self.lwMenu.isSortingEnabled()
        self.lwMenu.setSortingEnabled(False)
        item = self.lwMenu.item(0)
        item.setText(_translate("Dialog", "General"))
        item.setToolTip(_translate("Dialog", "General"))
        item = self.lwMenu.item(1)
        item.setText(_translate("Dialog", "Style"))
        item.setToolTip(_translate("Dialog", " Style"))
        item = self.lwMenu.item(2)
        item.setText(_translate("Dialog", "Build & Run"))
        self.lwMenu.setSortingEnabled(__sortingEnabled)
        self.tabWidgetSettings.setTabText(self.tabWidgetSettings.indexOf(self.tabEditorsettings), _translate("Dialog", "Editor settings"))
        self.rbLightStyle.setText(_translate("Dialog", "White style"))
        self.rbDarkStyle.setText(_translate("Dialog", "Dark style"))
        self.codeEdit.setPlainText(_translate("Dialog", "      *******************************************************************\n"
"      ** Example taken from http://progopedia.com/version/opencobol-1.0/*\n"
"      *******************************************************************\n"
"       IDENTIFICATION DIVISION.\n"
"      **************************************\n"
"       PROGRAM-ID. SAMPLE.\n"
"      **\n"
"       DATA DIVISION.\n"
"      **************************************\n"
"       WORKING-STORAGE SECTION.\n"
"      *-*-*-*-*-*-*-*-*-*-*-*-*-*\n"
"       77 FACT      PIC 9(15) comp  .\n"
"       77 N         PIC 99          .\n"
"       77 I         PIC 99          .\n"
"       77 IST       PIC XX          .\n"
"       77 FACTTST   PIC X(18)       .\n"
"      **\n"
"       PROCEDURE DIVISION.\n"
"      **************************************\n"
"       MAIN-PROCECURE.\n"
"           MOVE 16 to N\n"
"           MOVE 0 to I\n"
"           MOVE 1 to FACT\n"
"           PERFORM UNTIL I GREATER THAN N\n"
"               MOVE I to IST\n"
"               MOVE FACT to FACTTST\n"
"               DISPLAY IST \"! = \" FACTTST\n"
"               ADD 1 to I\n"
"               MULTIPLY I BY FACT\n"
"                    ON SIZE ERROR DISPLAY \"value too big\"\n"
"               END-MULTIPLY\n"
"           END-PERFORM\n"
"           EXIT PROGRAM.\n"
"       END PROGRAM SAMPLE.\n"
"      **\n"
""))
        self.tabWidgetStyle.setTabText(self.tabWidgetStyle.indexOf(self.tab), _translate("Dialog", "Editor"))
        self.label.setText(_translate("Dialog", "Background"))
        self.label_2.setText(_translate("Dialog", "Foreground"))
        self.label_3.setText(_translate("Dialog", "User input"))
        self.label_4.setText(_translate("Dialog", "Application output"))
        self.tabWidgetStyle.setTabText(self.tabWidgetStyle.indexOf(self.tab_2), _translate("Dialog", "Console"))
        self.radioButtonWhite.setText(_translate("Dialog", "White"))
        self.radioButtonDark.setText(_translate("Dialog", "Dark"))
        self.homeWidget.setProperty("title", _translate("Dialog", "Welcome to OpenCoblIDE"))
        self.tabWidgetStyle.setTabText(self.tabWidgetStyle.indexOf(self.tab_3), _translate("Dialog", "Home page"))
        self.label_6.setText(_translate("Dialog", "Run program in external terminal:"))
        self.labelShellCmd.setText(_translate("Dialog", "External terminal:"))

from oci.editor import QCobolCodeEdit
from pyqode.widgets import QHomeWidget, QColorButton, QInteractiveConsole, QPropertyGrid
from . import ide_rc