# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/Projects/OpenCobolIDE/forms/dlg_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from pyqode.qt import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 1024)
        Dialog.setMinimumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ide-icons/rc/silex-192x192.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 6, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QGridLayout(self.widget)
        self.widget_2.setContentsMargins(0, 0, 0, 0)
        self.widget_2.setSpacing(0)
        self.widget_2.setObjectName("widget_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabEditor = QtWidgets.QWidget()
        self.tabEditor.setObjectName("tabEditor")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabEditor)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tabEditor)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1244, 921))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.checkBoxViewLineNumber = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxViewLineNumber.setText("")
        self.checkBoxViewLineNumber.setChecked(True)
        self.checkBoxViewLineNumber.setObjectName("checkBoxViewLineNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBoxViewLineNumber)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.checkBoxHighlightCurrentLine = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxHighlightCurrentLine.setText("")
        self.checkBoxHighlightCurrentLine.setChecked(True)
        self.checkBoxHighlightCurrentLine.setObjectName("checkBoxHighlightCurrentLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxHighlightCurrentLine)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.checkBoxHighlightWhitespaces = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxHighlightWhitespaces.setText("")
        self.checkBoxHighlightWhitespaces.setChecked(True)
        self.checkBoxHighlightWhitespaces.setObjectName("checkBoxHighlightWhitespaces")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBoxHighlightWhitespaces)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.checkBoxShowErrors = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxShowErrors.setText("")
        self.checkBoxShowErrors.setObjectName("checkBoxShowErrors")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBoxShowErrors)
        self.label_38 = QtWidgets.QLabel(self.groupBox_3)
        self.label_38.setObjectName("label_38")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.cb_cursor_pos_in_bytes = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_cursor_pos_in_bytes.setText("")
        self.cb_cursor_pos_in_bytes.setObjectName("cb_cursor_pos_in_bytes")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cb_cursor_pos_in_bytes)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_11 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.groupBox_11)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.spin_box_margin_1 = QtWidgets.QSpinBox(self.groupBox_11)
        self.spin_box_margin_1.setObjectName("spin_box_margin_1")
        self.horizontalLayout_14.addWidget(self.spin_box_margin_1)
        self.color_picker_1 = ColorPicker(self.groupBox_11)
        self.color_picker_1.setText("")
        self.color_picker_1.setObjectName("color_picker_1")
        self.horizontalLayout_14.addWidget(self.color_picker_1)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_39 = QtWidgets.QLabel(self.groupBox_11)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_15.addWidget(self.label_39)
        self.spin_box_margin_2 = QtWidgets.QSpinBox(self.groupBox_11)
        self.spin_box_margin_2.setObjectName("spin_box_margin_2")
        self.horizontalLayout_15.addWidget(self.spin_box_margin_2)
        self.color_picker_2 = ColorPicker(self.groupBox_11)
        self.color_picker_2.setText("")
        self.color_picker_2.setObjectName("color_picker_2")
        self.horizontalLayout_15.addWidget(self.color_picker_2)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_40 = QtWidgets.QLabel(self.groupBox_11)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_16.addWidget(self.label_40)
        self.spin_box_margin_3 = QtWidgets.QSpinBox(self.groupBox_11)
        self.spin_box_margin_3.setObjectName("spin_box_margin_3")
        self.horizontalLayout_16.addWidget(self.spin_box_margin_3)
        self.color_picker_3 = ColorPicker(self.groupBox_11)
        self.color_picker_3.setText("")
        self.color_picker_3.setObjectName("color_picker_3")
        self.horizontalLayout_16.addWidget(self.color_picker_3)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_41 = QtWidgets.QLabel(self.groupBox_11)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_17.addWidget(self.label_41)
        self.spin_box_margin_4 = QtWidgets.QSpinBox(self.groupBox_11)
        self.spin_box_margin_4.setObjectName("spin_box_margin_4")
        self.horizontalLayout_17.addWidget(self.spin_box_margin_4)
        self.color_picker_4 = ColorPicker(self.groupBox_11)
        self.color_picker_4.setText("")
        self.color_picker_4.setObjectName("color_picker_4")
        self.horizontalLayout_17.addWidget(self.color_picker_4)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.verticalLayout_7.addWidget(self.groupBox_11)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEditCommentIndicator = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.lineEditCommentIndicator.setFont(font)
        self.lineEditCommentIndicator.setObjectName("lineEditCommentIndicator")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditCommentIndicator)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBoxEditorTabLen = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxEditorTabLen.setMinimum(2)
        self.spinBoxEditorTabLen.setMaximum(99)
        self.spinBoxEditorTabLen.setProperty("value", 4)
        self.spinBoxEditorTabLen.setObjectName("spinBoxEditorTabLen")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxEditorTabLen)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.checkBoxEditorAutoIndent = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxEditorAutoIndent.setChecked(True)
        self.checkBoxEditorAutoIndent.setObjectName("checkBoxEditorAutoIndent")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBoxEditorAutoIndent)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.checkBoxSmartBackspace = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxSmartBackspace.setObjectName("checkBoxSmartBackspace")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBoxSmartBackspace)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBoxEditorCCTriggerLen = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxEditorCCTriggerLen.setProperty("value", 1)
        self.spinBoxEditorCCTriggerLen.setObjectName("spinBoxEditorCCTriggerLen")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxEditorCCTriggerLen)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbLowerCaseKwds = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbLowerCaseKwds.setObjectName("rbLowerCaseKwds")
        self.horizontalLayout.addWidget(self.rbLowerCaseKwds)
        self.rbUpperCaseKwds = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbUpperCaseKwds.setChecked(True)
        self.rbUpperCaseKwds.setObjectName("rbUpperCaseKwds")
        self.horizontalLayout.addWidget(self.rbUpperCaseKwds)
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.comboCcFilterMode = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCcFilterMode.sizePolicy().hasHeightForWidth())
        self.comboCcFilterMode.setSizePolicy(sizePolicy)
        self.comboCcFilterMode.setMinimumSize(QtCore.QSize(134, 0))
        self.comboCcFilterMode.setObjectName("comboCcFilterMode")
        self.comboCcFilterMode.addItem("")
        self.comboCcFilterMode.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboCcFilterMode)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayout_11 = QtWidgets.QFormLayout(self.groupBox_10)
        self.formLayout_11.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_30 = QtWidgets.QLabel(self.groupBox_10)
        self.label_30.setObjectName("label_30")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.comboBoxPreferredEOL = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBoxPreferredEOL.setObjectName("comboBoxPreferredEOL")
        self.comboBoxPreferredEOL.addItem("")
        self.comboBoxPreferredEOL.addItem("")
        self.comboBoxPreferredEOL.addItem("")
        self.comboBoxPreferredEOL.addItem("")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxPreferredEOL)
        self.checkBoxAutodetectEOL = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBoxAutodetectEOL.setChecked(True)
        self.checkBoxAutodetectEOL.setObjectName("checkBoxAutodetectEOL")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxAutodetectEOL)
        self.verticalLayout_7.addWidget(self.groupBox_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ide-icons/rc/cobol-mimetype.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabEditor, icon1, "")
        self.tabStyle = QtWidgets.QWidget()
        self.tabStyle.setObjectName("tabStyle")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabStyle)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabStyle)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.radioButtonColorWhite = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButtonColorWhite.setChecked(True)
        self.radioButtonColorWhite.setObjectName("radioButtonColorWhite")
        self.horizontalLayout_3.addWidget(self.radioButtonColorWhite)
        self.radioButtonColorDark = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButtonColorDark.setObjectName("radioButtonColorDark")
        self.horizontalLayout_3.addWidget(self.radioButtonColorDark)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.layoutIconTheme = QtWidgets.QFormLayout()
        self.layoutIconTheme.setContentsMargins(-1, 0, -1, -1)
        self.layoutIconTheme.setObjectName("layoutIconTheme")
        self.lblIconTheme = QtWidgets.QLabel(self.groupBox_5)
        self.lblIconTheme.setObjectName("lblIconTheme")
        self.layoutIconTheme.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblIconTheme)
        self.comboBoxIconTheme = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBoxIconTheme.setObjectName("comboBoxIconTheme")
        self.layoutIconTheme.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxIconTheme)
        self.verticalLayout_2.addLayout(self.layoutIconTheme)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabStyle)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBox_6)
        self.fontComboBox.setFontFilters(QtWidgets.QFontComboBox.MonospacedFonts)
        font = QtGui.QFont()
        font.setFamily("Clean")
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.horizontalLayout_4.addWidget(self.fontComboBox)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.spinBoxFontSize = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBoxFontSize.setProperty("value", 10)
        self.spinBoxFontSize.setObjectName("spinBoxFontSize")
        self.horizontalLayout_5.addWidget(self.spinBoxFontSize)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabStyle)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidgetColorSchemes = QtWidgets.QListWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetColorSchemes.sizePolicy().hasHeightForWidth())
        self.listWidgetColorSchemes.setSizePolicy(sizePolicy)
        self.listWidgetColorSchemes.setObjectName("listWidgetColorSchemes")
        self.gridLayout_4.addWidget(self.listWidgetColorSchemes, 0, 0, 1, 1)
        self.plainTextEdit = CobolCodeEdit(self.groupBox_7)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        icon = QtGui.QIcon.fromTheme("applications-graphics")
        self.tabWidget.addTab(self.tabStyle, icon, "")
        self.tabCompiler = QtWidgets.QWidget()
        self.tabCompiler.setObjectName("tabCompiler")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tabCompiler)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tabCompiler)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 1224, 973))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.formLayout_6 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_7)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setContentsMargins(9, 9, 9, 9)
        self.formLayout_6.setSpacing(9)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_compiler_path = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_compiler_path.setObjectName("label_compiler_path")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_compiler_path)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEditCompilerPath = PathLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEditCompilerPath.setObjectName("lineEditCompilerPath")
        self.horizontalLayout_9.addWidget(self.lineEditCompilerPath)
        self.toolButtonCustomCompilerPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        self.toolButtonCustomCompilerPath.setObjectName("toolButtonCustomCompilerPath")
        self.horizontalLayout_9.addWidget(self.toolButtonCustomCompilerPath)
        self.toolButtonCheckCompiler = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        icon = QtGui.QIcon.fromTheme("emblem-checked")
        self.toolButtonCheckCompiler.setIcon(icon)
        self.toolButtonCheckCompiler.setObjectName("toolButtonCheckCompiler")
        self.horizontalLayout_9.addWidget(self.toolButtonCheckCompiler)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.groupBoxEnvVars = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_7)
        self.groupBoxEnvVars.setObjectName("groupBoxEnvVars")
        self.formLayout_12 = QtWidgets.QFormLayout(self.groupBoxEnvVars)
        self.formLayout_12.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setObjectName("formLayout_12")
        self.PATH = PathLineEdit(self.groupBoxEnvVars)
        self.PATH.setObjectName("PATH")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PATH)
        self.COB_CONFIG_DIR = PathLineEdit(self.groupBoxEnvVars)
        self.COB_CONFIG_DIR.setObjectName("COB_CONFIG_DIR")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.COB_CONFIG_DIR)
        self.COB_COPY_DIR = PathLineEdit(self.groupBoxEnvVars)
        self.COB_COPY_DIR.setObjectName("COB_COPY_DIR")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.COB_COPY_DIR)
        self.COB_INCLUDE_PATH = PathLineEdit(self.groupBoxEnvVars)
        self.COB_INCLUDE_PATH.setObjectName("COB_INCLUDE_PATH")
        self.formLayout_12.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.COB_INCLUDE_PATH)
        self.COB_LIB_PATH = PathLineEdit(self.groupBoxEnvVars)
        self.COB_LIB_PATH.setObjectName("COB_LIB_PATH")
        self.formLayout_12.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.COB_LIB_PATH)
        self.cbPATH = QtWidgets.QCheckBox(self.groupBoxEnvVars)
        self.cbPATH.setObjectName("cbPATH")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cbPATH)
        self.cbCOB_CONFIG_DIR = QtWidgets.QCheckBox(self.groupBoxEnvVars)
        self.cbCOB_CONFIG_DIR.setObjectName("cbCOB_CONFIG_DIR")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cbCOB_CONFIG_DIR)
        self.cbCOB_COPY_DIR = QtWidgets.QCheckBox(self.groupBoxEnvVars)
        self.cbCOB_COPY_DIR.setObjectName("cbCOB_COPY_DIR")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cbCOB_COPY_DIR)
        self.cbCOB_INCLUDE_PATH = QtWidgets.QCheckBox(self.groupBoxEnvVars)
        self.cbCOB_INCLUDE_PATH.setObjectName("cbCOB_INCLUDE_PATH")
        self.formLayout_12.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.cbCOB_INCLUDE_PATH)
        self.cbCOB_LIB_PATH = QtWidgets.QCheckBox(self.groupBoxEnvVars)
        self.cbCOB_LIB_PATH.setObjectName("cbCOB_LIB_PATH")
        self.formLayout_12.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.cbCOB_LIB_PATH)
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.groupBoxEnvVars)
        self.cbAutoDetectSublmodules = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cbAutoDetectSublmodules.setObjectName("cbAutoDetectSublmodules")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbAutoDetectSublmodules)
        self.labelVCVARS = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.labelVCVARS.setObjectName("labelVCVARS")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelVCVARS)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEditVCVARS = PathLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEditVCVARS.setObjectName("lineEditVCVARS")
        self.horizontalLayout_8.addWidget(self.lineEditVCVARS)
        self.toolButtonVCVARS = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        self.toolButtonVCVARS.setObjectName("toolButtonVCVARS")
        self.horizontalLayout_8.addWidget(self.toolButtonVCVARS)
        self.combo_arch = QtWidgets.QComboBox(self.scrollAreaWidgetContents_7)
        self.combo_arch.setEditable(False)
        self.combo_arch.setObjectName("combo_arch")
        self.combo_arch.addItem("")
        self.combo_arch.addItem("")
        self.horizontalLayout_8.addWidget(self.combo_arch)
        self.formLayout_6.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.lineEditOutputDirectory = PathLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEditOutputDirectory.setObjectName("lineEditOutputDirectory")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditOutputDirectory)
        self.cb_copy_runtime_dlls = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_copy_runtime_dlls.setObjectName("cb_copy_runtime_dlls")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cb_copy_runtime_dlls)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_32.setObjectName("label_32")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.lineEditCobcExts = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEditCobcExts.setObjectName("lineEditCobcExts")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEditCobcExts)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_8.setObjectName("label_8")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBoxStandard = QtWidgets.QComboBox(self.scrollAreaWidgetContents_7)
        self.comboBoxStandard.setObjectName("comboBoxStandard")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBoxStandard)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.checkBoxFreeFormat = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBoxFreeFormat.setText("")
        self.checkBoxFreeFormat.setObjectName("checkBoxFreeFormat")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.checkBoxFreeFormat)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cb_ftrace = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_ftrace.setObjectName("cb_ftrace")
        self.gridLayout_5.addWidget(self.cb_ftrace, 2, 1, 1, 1)
        self.cb_static = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_static.setObjectName("cb_static")
        self.gridLayout_5.addWidget(self.cb_static, 0, 1, 1, 1)
        self.cb_g = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_g.setObjectName("cb_g")
        self.gridLayout_5.addWidget(self.cb_g, 0, 3, 1, 1)
        self.cb_debugging_line = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_debugging_line.setObjectName("cb_debugging_line")
        self.gridLayout_5.addWidget(self.cb_debugging_line, 2, 3, 1, 1)
        self.cb_ftraceall = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_ftraceall.setObjectName("cb_ftraceall")
        self.gridLayout_5.addWidget(self.cb_ftraceall, 2, 2, 1, 1)
        self.cb_debug = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_debug.setObjectName("cb_debug")
        self.gridLayout_5.addWidget(self.cb_debug, 0, 2, 1, 1)
        self.cb_w = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_w.setObjectName("cb_w")
        self.gridLayout_5.addWidget(self.cb_w, 0, 0, 1, 1)
        self.cb_wall = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_wall.setObjectName("cb_wall")
        self.gridLayout_5.addWidget(self.cb_wall, 2, 0, 1, 1)
        self.formLayout_6.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.gridLayout_5)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_37.setObjectName("label_37")
        self.formLayout_6.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.listWidgetCopyPaths = QtWidgets.QListWidget(self.scrollAreaWidgetContents_7)
        self.listWidgetCopyPaths.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidgetCopyPaths.setObjectName("listWidgetCopyPaths")
        self.horizontalLayout_12.addWidget(self.listWidgetCopyPaths)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btAddAbsoluteCopyPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        icon = QtGui.QIcon.fromTheme("folder-open")
        self.btAddAbsoluteCopyPath.setIcon(icon)
        self.btAddAbsoluteCopyPath.setObjectName("btAddAbsoluteCopyPath")
        self.verticalLayout_12.addWidget(self.btAddAbsoluteCopyPath)
        self.btAddRelativeCopyPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btAddRelativeCopyPath.setIcon(icon)
        self.btAddRelativeCopyPath.setObjectName("btAddRelativeCopyPath")
        self.verticalLayout_12.addWidget(self.btAddRelativeCopyPath)
        self.btRemoveCopyPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ide-icons/rc/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btRemoveCopyPath.setIcon(icon2)
        self.btRemoveCopyPath.setObjectName("btRemoveCopyPath")
        self.verticalLayout_12.addWidget(self.btRemoveCopyPath)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem4)
        self.horizontalLayout_12.addLayout(self.verticalLayout_12)
        self.formLayout_6.setLayout(13, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.listWidgetLibPaths = QtWidgets.QListWidget(self.scrollAreaWidgetContents_7)
        self.listWidgetLibPaths.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidgetLibPaths.setObjectName("listWidgetLibPaths")
        self.horizontalLayout_10.addWidget(self.listWidgetLibPaths)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolButtonAddLibPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ide-icons/rc/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAddLibPath.setIcon(icon3)
        self.toolButtonAddLibPath.setObjectName("toolButtonAddLibPath")
        self.verticalLayout_4.addWidget(self.toolButtonAddLibPath)
        self.toolButtonAddRelativeLibPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ide-icons/rc/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAddRelativeLibPath.setIcon(icon4)
        self.toolButtonAddRelativeLibPath.setObjectName("toolButtonAddRelativeLibPath")
        self.verticalLayout_4.addWidget(self.toolButtonAddRelativeLibPath)
        self.toolButtonRemoveLibPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        self.toolButtonRemoveLibPath.setIcon(icon2)
        self.toolButtonRemoveLibPath.setObjectName("toolButtonRemoveLibPath")
        self.verticalLayout_4.addWidget(self.toolButtonRemoveLibPath)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.formLayout_6.setLayout(14, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEditLibs = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEditLibs.setObjectName("lineEditLibs")
        self.formLayout_6.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEditLibs)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.le_compiler_flags = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        self.le_compiler_flags.setObjectName("le_compiler_flags")
        self.horizontalLayout_20.addWidget(self.le_compiler_flags)
        self.btCompilerFlagsHelp = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        self.btCompilerFlagsHelp.setObjectName("btCompilerFlagsHelp")
        self.horizontalLayout_20.addWidget(self.btCompilerFlagsHelp)
        self.formLayout_6.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_20)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_11.addWidget(self.scrollArea_5)
        icon = QtGui.QIcon.fromTheme("exec")
        self.tabWidget.addTab(self.tabCompiler, icon, "")
        self.tabRun = QtWidgets.QWidget()
        self.tabRun.setObjectName("tabRun")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabRun)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout_13 = QtWidgets.QFormLayout()
        self.formLayout_13.setContentsMargins(6, 6, 6, 6)
        self.formLayout_13.setObjectName("formLayout_13")
        self.lbl_external_terminal_command = QtWidgets.QLabel(self.tabRun)
        self.lbl_external_terminal_command.setObjectName("lbl_external_terminal_command")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_external_terminal_command)
        self.lineEditRunTerm = QtWidgets.QLineEdit(self.tabRun)
        self.lineEditRunTerm.setObjectName("lineEditRunTerm")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditRunTerm)
        self.label_42 = QtWidgets.QLabel(self.tabRun)
        self.label_42.setObjectName("label_42")
        self.formLayout_13.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.edit_working_dir = PathLineEdit(self.tabRun)
        self.edit_working_dir.setObjectName("edit_working_dir")
        self.horizontalLayout_19.addWidget(self.edit_working_dir)
        self.bt_working_dir = QtWidgets.QToolButton(self.tabRun)
        self.bt_working_dir.setObjectName("bt_working_dir")
        self.horizontalLayout_19.addWidget(self.bt_working_dir)
        self.formLayout_13.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.checkBoxRunExtTerm = QtWidgets.QCheckBox(self.tabRun)
        self.checkBoxRunExtTerm.setObjectName("checkBoxRunExtTerm")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxRunExtTerm)
        self.label_43 = QtWidgets.QLabel(self.tabRun)
        self.label_43.setObjectName("label_43")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.verticalLayout_10.addLayout(self.formLayout_13)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tabRun)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tw_run_env = QtWidgets.QTableWidget(self.groupBox_12)
        self.tw_run_env.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_run_env.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_run_env.setObjectName("tw_run_env")
        self.tw_run_env.setColumnCount(2)
        self.tw_run_env.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_run_env.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_run_env.setHorizontalHeaderItem(1, item)
        self.tw_run_env.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_run_env.horizontalHeader().setDefaultSectionSize(300)
        self.tw_run_env.horizontalHeader().setStretchLastSection(True)
        self.tw_run_env.verticalHeader().setVisible(False)
        self.horizontalLayout_13.addWidget(self.tw_run_env)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.bt_add_run_env = QtWidgets.QPushButton(self.groupBox_12)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_add_run_env.setIcon(icon)
        self.bt_add_run_env.setObjectName("bt_add_run_env")
        self.verticalLayout_14.addWidget(self.bt_add_run_env)
        self.bt_rm_run_env = QtWidgets.QPushButton(self.groupBox_12)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_rm_run_env.setIcon(icon)
        self.bt_rm_run_env.setObjectName("bt_rm_run_env")
        self.verticalLayout_14.addWidget(self.bt_rm_run_env)
        self.bt_clear_run_env = QtWidgets.QPushButton(self.groupBox_12)
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.bt_clear_run_env.setIcon(icon)
        self.bt_clear_run_env.setObjectName("bt_clear_run_env")
        self.verticalLayout_14.addWidget(self.bt_clear_run_env)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_14)
        self.verticalLayout_10.addWidget(self.groupBox_12)
        self.verticalLayout_10.setStretch(1, 1)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.tabWidget.addTab(self.tabRun, icon, "")
        self.tabSqlCobol = QtWidgets.QWidget()
        self.tabSqlCobol.setObjectName("tabSqlCobol")
        self.gridLayout = QtWidgets.QGridLayout(self.tabSqlCobol)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tabSqlCobol)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1244, 897))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidgetSQL = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents_5)
        self.stackedWidgetSQL.setObjectName("stackedWidgetSQL")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setObjectName("label_19")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditDbpre = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditDbpre.setObjectName("lineEditDbpre")
        self.horizontalLayout_2.addWidget(self.lineEditDbpre)
        self.toolButtonDbpre = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButtonDbpre.setObjectName("toolButtonDbpre")
        self.horizontalLayout_2.addWidget(self.toolButtonDbpre)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.labelDbpreVersion = QtWidgets.QLabel(self.groupBox_8)
        self.labelDbpreVersion.setStyleSheet("font: oblique 9pt \"Cantarell\";")
        self.labelDbpreVersion.setObjectName("labelDbpreVersion")
        self.verticalLayout_5.addWidget(self.labelDbpreVersion)
        self.formLayout_8.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_5)
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditCobmysqlapi = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditCobmysqlapi.setObjectName("lineEditCobmysqlapi")
        self.horizontalLayout_6.addWidget(self.lineEditCobmysqlapi)
        self.toolButtonCobMySqlApiPath = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButtonCobMySqlApiPath.setObjectName("toolButtonCobMySqlApiPath")
        self.horizontalLayout_6.addWidget(self.toolButtonCobMySqlApiPath)
        self.formLayout_8.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setObjectName("label_21")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditDbpreFramework = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditDbpreFramework.setObjectName("lineEditDbpreFramework")
        self.horizontalLayout_7.addWidget(self.lineEditDbpreFramework)
        self.toolButtonDbpreFramework = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButtonDbpreFramework.setObjectName("toolButtonDbpreFramework")
        self.horizontalLayout_7.addWidget(self.toolButtonDbpreFramework)
        self.formLayout_8.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_33 = QtWidgets.QLabel(self.groupBox_8)
        self.label_33.setObjectName("label_33")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.lineEditDbpreExts = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditDbpreExts.setObjectName("lineEditDbpreExts")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditDbpreExts)
        self.gridLayout_3.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.page)
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.groupBox_9)
        self.formLayout_9.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_22 = QtWidgets.QLabel(self.groupBox_9)
        self.label_22.setObjectName("label_22")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.lineEditDBHOST = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBHOST.setText("")
        self.lineEditDBHOST.setObjectName("lineEditDBHOST")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditDBHOST)
        self.label_23 = QtWidgets.QLabel(self.groupBox_9)
        self.label_23.setObjectName("label_23")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lineEditDBUSER = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBUSER.setObjectName("lineEditDBUSER")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditDBUSER)
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setObjectName("label_24")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEditDBPASSWD = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBPASSWD.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditDBPASSWD.setObjectName("lineEditDBPASSWD")
        self.verticalLayout_6.addWidget(self.lineEditDBPASSWD)
        self.checkBoxShowDbPass = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBoxShowDbPass.setObjectName("checkBoxShowDbPass")
        self.verticalLayout_6.addWidget(self.checkBoxShowDbPass)
        self.formLayout_9.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6)
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEditDBNAME = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBNAME.setText("")
        self.lineEditDBNAME.setObjectName("lineEditDBNAME")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditDBNAME)
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setObjectName("label_26")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEditDBPORT = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBPORT.setText("")
        self.lineEditDBPORT.setObjectName("lineEditDBPORT")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditDBPORT)
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setObjectName("label_27")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lineEditDBSOCKET = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBSOCKET.setText("")
        self.lineEditDBSOCKET.setObjectName("lineEditDBSOCKET")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditDBSOCKET)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_9.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem7)
        self.gridLayout_3.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.stackedWidgetSQL.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.formLayout_10 = QtWidgets.QFormLayout(self.page_2)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_29 = QtWidgets.QLabel(self.page_2)
        self.label_29.setObjectName("label_29")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEditESQLOC = QtWidgets.QLineEdit(self.page_2)
        self.lineEditESQLOC.setObjectName("lineEditESQLOC")
        self.horizontalLayout_11.addWidget(self.lineEditESQLOC)
        self.toolButtonESQLOC = QtWidgets.QToolButton(self.page_2)
        self.toolButtonESQLOC.setObjectName("toolButtonESQLOC")
        self.horizontalLayout_11.addWidget(self.toolButtonESQLOC)
        self.formLayout_10.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_34 = QtWidgets.QLabel(self.page_2)
        self.label_34.setObjectName("label_34")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.lineEditesqlOcExts = QtWidgets.QLineEdit(self.page_2)
        self.lineEditesqlOcExts.setObjectName("lineEditesqlOcExts")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditesqlOcExts)
        self.stackedWidgetSQL.addWidget(self.page_2)
        self.verticalLayout_9.addWidget(self.stackedWidgetSQL)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout.addWidget(self.scrollArea_3, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tabSqlCobol)
        self.label_28.setOpenExternalLinks(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ide-icons/rc/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabSqlCobol, icon5, "")
        self.widget_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.stackedWidgetSQL.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.widget.setAccessibleName(_translate("Dialog", "widget", "widget"))
        self.groupBox_3.setTitle(_translate("Dialog", "View"))
        self.label_10.setText(_translate("Dialog", "Display line numbers:"))
        self.checkBoxViewLineNumber.setToolTip(_translate("Dialog", "Show/Hide line numbers"))
        self.checkBoxViewLineNumber.setStatusTip(_translate("Dialog", "Show/Hide line numbers"))
        self.label_11.setText(_translate("Dialog", "Highlight current line:"))
        self.checkBoxHighlightCurrentLine.setToolTip(_translate("Dialog", "Highlight caret line"))
        self.checkBoxHighlightCurrentLine.setStatusTip(_translate("Dialog", "Highlight caret line"))
        self.label_12.setText(_translate("Dialog", "Highlight whitespaces:"))
        self.checkBoxHighlightWhitespaces.setToolTip(_translate("Dialog", "Show visual whitespaces"))
        self.checkBoxHighlightWhitespaces.setStatusTip(_translate("Dialog", "Show visual whitespaces"))
        self.label_13.setText(_translate("Dialog", "Show errors:"))
        self.checkBoxShowErrors.setToolTip(_translate("Dialog", "Compile your code on the fly and show errors while you\'re typing"))
        self.label_38.setText(_translate("Dialog", "Show cursor position in bytes:"))
        self.cb_cursor_pos_in_bytes.setToolTip(_translate("Dialog", "<html><head/><body><p>Check this if you want to see the cursor position expressed in bytes instead of characters (encoding is then taken into account).</p></body></html>"))
        self.groupBox_11.setTitle(_translate("Dialog", "Margins"))
        self.label_5.setText(_translate("Dialog", "Margin 1:"))
        self.label_39.setText(_translate("Dialog", "Margin 2:"))
        self.label_40.setText(_translate("Dialog", "Margin 3:"))
        self.label_41.setText(_translate("Dialog", "Margin 4:"))
        self.groupBox.setTitle(_translate("Dialog", "Comments"))
        self.label_7.setText(_translate("Dialog", "Symbol"))
        self.lineEditCommentIndicator.setText(_translate("Dialog", "*>"))
        self.groupBox_2.setTitle(_translate("Dialog", "Indentation"))
        self.label.setText(_translate("Dialog", "Width:"))
        self.spinBoxEditorTabLen.setToolTip(_translate("Dialog", "Tab length (number of spaces)"))
        self.spinBoxEditorTabLen.setStatusTip(_translate("Dialog", "Tab length (number of spaces)"))
        self.checkBoxEditorAutoIndent.setToolTip(_translate("Dialog", "Enable/Disable automatic indentation"))
        self.checkBoxEditorAutoIndent.setStatusTip(_translate("Dialog", "Enable/Disable automatic indentation"))
        self.checkBoxEditorAutoIndent.setText(_translate("Dialog", "Automatic indentation"))
        self.checkBoxSmartBackspace.setToolTip(_translate("Dialog", "Backspace will act as shift+tab, i.e. it will eat as much spaces \n"
"as possible to get back to the previous indentation level."))
        self.checkBoxSmartBackspace.setText(_translate("Dialog", "Intelligent backspace"))
        self.groupBox_4.setTitle(_translate("Dialog", "Code completion"))
        self.label_2.setText(_translate("Dialog", "Trigger length:"))
        self.spinBoxEditorCCTriggerLen.setToolTip(_translate("Dialog", "Number of characters needed to trigger auto completion"))
        self.spinBoxEditorCCTriggerLen.setStatusTip(_translate("Dialog", "Number of characters needed to trigger auto completion"))
        self.label_16.setText(_translate("Dialog", "Proposed keywords:"))
        self.rbLowerCaseKwds.setToolTip(_translate("Dialog", "All proposed keywords are lower-case"))
        self.rbLowerCaseKwds.setText(_translate("Dialog", "&lower-case"))
        self.rbUpperCaseKwds.setToolTip(_translate("Dialog", "All proposed keywords are UPPER-CASE"))
        self.rbUpperCaseKwds.setText(_translate("Dialog", "&UPPER-CASE"))
        self.label_31.setText(_translate("Dialog", "Filter mode:"))
        self.comboCcFilterMode.setItemText(0, _translate("Dialog", "Prefix (faster)"))
        self.comboCcFilterMode.setItemText(1, _translate("Dialog", "Subsequence (smarter)"))
        self.groupBox_10.setTitle(_translate("Dialog", "EOL"))
        self.label_30.setText(_translate("Dialog", "Preferred EOL:"))
        self.comboBoxPreferredEOL.setItemText(0, _translate("Dialog", "System"))
        self.comboBoxPreferredEOL.setItemText(1, _translate("Dialog", "Linux"))
        self.comboBoxPreferredEOL.setItemText(2, _translate("Dialog", "Mac"))
        self.comboBoxPreferredEOL.setItemText(3, _translate("Dialog", "Windows"))
        self.checkBoxAutodetectEOL.setText(_translate("Dialog", "Auto detect EOL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEditor), _translate("Dialog", "Editor"))
        self.groupBox_5.setTitle(_translate("Dialog", "Application style"))
        self.radioButtonColorWhite.setToolTip(_translate("Dialog", "Use native style"))
        self.radioButtonColorWhite.setStatusTip(_translate("Dialog", "Use native style"))
        self.radioButtonColorWhite.setText(_translate("Dialog", "&Native"))
        self.radioButtonColorDark.setToolTip(_translate("Dialog", "Use a global dark style (using QDarkStyleSheet)"))
        self.radioButtonColorDark.setStatusTip(_translate("Dialog", "Use a global dark style (using QDarkStyleSheet)"))
        self.radioButtonColorDark.setText(_translate("Dialog", "Dark"))
        self.lblIconTheme.setText(_translate("Dialog", "Icon theme:"))
        self.groupBox_6.setTitle(_translate("Dialog", "Editor font"))
        self.label_3.setText(_translate("Dialog", "Editor font:"))
        self.fontComboBox.setToolTip(_translate("Dialog", "Change editor font"))
        self.fontComboBox.setStatusTip(_translate("Dialog", "Change editor font"))
        self.label_4.setText(_translate("Dialog", "Font size:"))
        self.spinBoxFontSize.setToolTip(_translate("Dialog", "Change editor font size"))
        self.spinBoxFontSize.setStatusTip(_translate("Dialog", "Change editor font size"))
        self.groupBox_7.setTitle(_translate("Dialog", "Editor color scheme"))
        self.listWidgetColorSchemes.setToolTip(_translate("Dialog", "Pygments color schemes."))
        self.listWidgetColorSchemes.setStatusTip(_translate("Dialog", "Pygments color schemes."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStyle), _translate("Dialog", "Style"))
        self.label_compiler_path.setText(_translate("Dialog", "Compiler path:"))
        self.lineEditCompilerPath.setToolTip(_translate("Dialog", "<html><head/><body><p>GnuCOBOL compiler path (complete path or executable name if correct path is defined in PATH).</p></body></html>"))
        self.lineEditCompilerPath.setStatusTip(_translate("Dialog", "Full path to the GnuCOBOL compiler."))
        self.toolButtonCustomCompilerPath.setText(_translate("Dialog", "..."))
        self.toolButtonCheckCompiler.setText(_translate("Dialog", "Check compiler"))
        self.groupBoxEnvVars.setTitle(_translate("Dialog", "Environment variables"))
        self.cbPATH.setText(_translate("Dialog", "PATH:"))
        self.cbCOB_CONFIG_DIR.setText(_translate("Dialog", "COB_CONFIG_DIR:"))
        self.cbCOB_COPY_DIR.setText(_translate("Dialog", "COB_COPY_DIR:"))
        self.cbCOB_INCLUDE_PATH.setText(_translate("Dialog", "COB_INCLUDE_PATH:"))
        self.cbCOB_LIB_PATH.setText(_translate("Dialog", "COB_LIB_PATH:"))
        self.cbAutoDetectSublmodules.setToolTip(_translate("Dialog", "<html><head/><body><p>If checked, the IDE will recursively look for CALL PROGRAM statements to build a list of submodules that will be automatically compiled when you\'re compiling the main program.</p></body></html>"))
        self.cbAutoDetectSublmodules.setText(_translate("Dialog", "Auto-detect and compile submodules"))
        self.labelVCVARS.setText(_translate("Dialog", "VCVARSALL path:"))
        self.lineEditVCVARS.setToolTip(_translate("Dialog", "<html><head/><body><p>Path to VCVARSALL.bat. It is needed if you\'re using a GnuCOBOL compiler built with Visual Studio.</p><p><br/>The VCVARSALL.bat file is located under the VC directory of you Visual Studio installation. Make sure to use the same version as the one used to build the compiler!</p></body></html>"))
        self.toolButtonVCVARS.setText(_translate("Dialog", "..."))
        self.combo_arch.setItemText(0, _translate("Dialog", "x86"))
        self.combo_arch.setItemText(1, _translate("Dialog", "x64"))
        self.label_36.setText(_translate("Dialog", "Output directory:"))
        self.cb_copy_runtime_dlls.setText(_translate("Dialog", "Copy runtime dlls to output directory"))
        self.label_32.setText(_translate("Dialog", "Associated extensions:"))
        self.label_8.setText(_translate("Dialog", "Standard:"))
        self.comboBoxStandard.setItemText(0, _translate("Dialog", "default"))
        self.comboBoxStandard.setItemText(1, _translate("Dialog", "cobol2002"))
        self.comboBoxStandard.setItemText(2, _translate("Dialog", "cobol85"))
        self.comboBoxStandard.setItemText(3, _translate("Dialog", "ibm"))
        self.comboBoxStandard.setItemText(4, _translate("Dialog", "mvs"))
        self.comboBoxStandard.setItemText(5, _translate("Dialog", "bs2000"))
        self.comboBoxStandard.setItemText(6, _translate("Dialog", "mf"))
        self.comboBoxStandard.setItemText(7, _translate("Dialog", "cobol2014"))
        self.comboBoxStandard.setItemText(8, _translate("Dialog", "acu"))
        self.comboBoxStandard.setItemText(9, _translate("Dialog", "none"))
        self.label_9.setText(_translate("Dialog", "Free format:"))
        self.checkBoxFreeFormat.setToolTip(_translate("Dialog", "Code and compile with free format support"))
        self.label_15.setText(_translate("Dialog", "Compiler flags"))
        self.cb_ftrace.setToolTip(_translate("Dialog", "<html><head/><body><p>Generate trace code</p><p>   - Executed SECTION/PARAGRAPH</p></body></html>"))
        self.cb_ftrace.setText(_translate("Dialog", "-ftrace"))
        self.cb_static.setToolTip(_translate("Dialog", "Link statically"))
        self.cb_static.setText(_translate("Dialog", "-static"))
        self.cb_g.setToolTip(_translate("Dialog", "Enable C compiler debug / stack check / trace"))
        self.cb_g.setText(_translate("Dialog", "-g"))
        self.cb_debugging_line.setToolTip(_translate("Dialog", "<html><head/><body><p>Enable debugging lines</p><p>  - \'D\' in indicator column or floating &gt;&gt;D</p></body></html>"))
        self.cb_debugging_line.setText(_translate("Dialog", "-fdebugging-line"))
        self.cb_ftraceall.setToolTip(_translate("Dialog", "<html><head/><body><p>Generate trace code</p><p>  - Executed SECTION/PARAGRAPH/STATEMENTS</p><p>  - Turned on by -debug</p></body></html>"))
        self.cb_ftraceall.setText(_translate("Dialog", "-ftraceall"))
        self.cb_debug.setText(_translate("Dialog", "-debug"))
        self.cb_w.setToolTip(_translate("Dialog", "Enable all warnings"))
        self.cb_w.setText(_translate("Dialog", "-W"))
        self.cb_wall.setToolTip(_translate("Dialog", "Enable most warnings"))
        self.cb_wall.setText(_translate("Dialog", "-Wall"))
        self.label_35.setText(_translate("Dialog", "Extra compiler flags"))
        self.label_37.setText(_translate("Dialog", "Copybook paths:"))
        self.listWidgetCopyPaths.setToolTip(_translate("Dialog", "The list of copybooks paths. You can use drag & drop to reorder them."))
        self.btAddAbsoluteCopyPath.setText(_translate("Dialog", "..."))
        self.btAddRelativeCopyPath.setText(_translate("Dialog", "..."))
        self.btRemoveCopyPath.setText(_translate("Dialog", "..."))
        self.label_17.setText(_translate("Dialog", "Library paths:"))
        self.listWidgetLibPaths.setToolTip(_translate("Dialog", "The list of library paths. You can use drag & drop to reorder them."))
        self.toolButtonAddLibPath.setToolTip(_translate("Dialog", "Add an absolute library path"))
        self.toolButtonAddLibPath.setText(_translate("Dialog", "..."))
        self.toolButtonAddRelativeLibPath.setToolTip(_translate("Dialog", "Add a relative library path"))
        self.toolButtonAddRelativeLibPath.setText(_translate("Dialog", "..."))
        self.toolButtonRemoveLibPath.setText(_translate("Dialog", "..."))
        self.label_18.setText(_translate("Dialog", "Libraries"))
        self.lineEditLibs.setToolTip(_translate("Dialog", "<html><head/><body><p>Add the libraries you would like your programs to link with here (-l option)</p></body></html>"))
        self.le_compiler_flags.setToolTip(_translate("Dialog", "You can add other compiler flags here"))
        self.btCompilerFlagsHelp.setText(_translate("Dialog", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCompiler), _translate("Dialog", "Compiler"))
        self.lbl_external_terminal_command.setText(_translate("Dialog", "External terminal command:"))
        self.lineEditRunTerm.setToolTip(_translate("Dialog", "External terminal command (filename is appended at the end of the command)"))
        self.lineEditRunTerm.setStatusTip(_translate("Dialog", "External terminal command"))
        self.label_42.setText(_translate("Dialog", "Working Directory:"))
        self.bt_working_dir.setText(_translate("Dialog", "..."))
        self.checkBoxRunExtTerm.setText(_translate("Dialog", "Run in external terminal"))
        self.label_43.setText(_translate("Dialog", "Terminal mode:"))
        self.groupBox_12.setTitle(_translate("Dialog", "Environment"))
        item = self.tw_run_env.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Key"))
        item = self.tw_run_env.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value"))
        self.bt_add_run_env.setText(_translate("Dialog", "Add "))
        self.bt_rm_run_env.setText(_translate("Dialog", "Remove"))
        self.bt_clear_run_env.setText(_translate("Dialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRun), _translate("Dialog", "Run"))
        self.groupBox_8.setTitle(_translate("Dialog", "DBPRE Configuration"))
        self.label_19.setText(_translate("Dialog", "dbpre"))
        self.toolButtonDbpre.setText(_translate("Dialog", "..."))
        self.labelDbpreVersion.setText(_translate("Dialog", "invalid dbpre executable"))
        self.label_20.setText(_translate("Dialog", "cobmysqlapi:"))
        self.toolButtonCobMySqlApiPath.setText(_translate("Dialog", "..."))
        self.label_21.setText(_translate("Dialog", "Framework:"))
        self.toolButtonDbpreFramework.setText(_translate("Dialog", "..."))
        self.label_33.setText(_translate("Dialog", "Associated extensions:"))
        self.groupBox_9.setTitle(_translate("Dialog", "DB Connection Parameters"))
        self.label_22.setText(_translate("Dialog", "DBHOST:"))
        self.label_23.setText(_translate("Dialog", "DBUSER:"))
        self.label_24.setText(_translate("Dialog", "DBPASSWD:"))
        self.checkBoxShowDbPass.setText(_translate("Dialog", "Show password"))
        self.label_25.setText(_translate("Dialog", "DBNAME:"))
        self.label_26.setText(_translate("Dialog", "DBPORT:"))
        self.label_27.setText(_translate("Dialog", "DBSOCKET:"))
        self.label_29.setText(_translate("Dialog", "esqlOC folder:"))
        self.toolButtonESQLOC.setText(_translate("Dialog", "..."))
        self.label_34.setText(_translate("Dialog", "Associated extensions:"))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Read the <a href=\"http://opencobolide.readthedocs.org/en/latest/advanced.html#how-to-setup-dbpre-integration-with-opencobolide\"><span style=\" text-decoration: underline; color:#2980b9;\">guide</span></a> to get started</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSqlCobol), _translate("Dialog", "SQL COBOL"))

from open_cobol_ide.view.editors import CobolCodeEdit
from open_cobol_ide.view.widgets import ColorPicker, PathLineEdit
from . import ide_rc