# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/Dev/OpenCobolIDE/forms/dlg_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from pyqode.qt import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(677, 691)
        Dialog.setMinimumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon.fromTheme("preferences-system")
        Dialog.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QGridLayout(self.widget)
        self.widget_2.setSpacing(0)
        self.widget_2.setContentsMargins(0, 0, 0, 0)
        self.widget_2.setObjectName("widget_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabEditor = QtWidgets.QWidget()
        self.tabEditor.setObjectName("tabEditor")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabEditor)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tabEditor)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -43, 621, 632))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.checkBoxViewLineNumber = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxViewLineNumber.setText("")
        self.checkBoxViewLineNumber.setChecked(True)
        self.checkBoxViewLineNumber.setObjectName("checkBoxViewLineNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBoxViewLineNumber)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.checkBoxHighlightCurrentLine = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxHighlightCurrentLine.setText("")
        self.checkBoxHighlightCurrentLine.setChecked(True)
        self.checkBoxHighlightCurrentLine.setObjectName("checkBoxHighlightCurrentLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxHighlightCurrentLine)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.checkBoxHighlightWhitespaces = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxHighlightWhitespaces.setText("")
        self.checkBoxHighlightWhitespaces.setChecked(True)
        self.checkBoxHighlightWhitespaces.setObjectName("checkBoxHighlightWhitespaces")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBoxHighlightWhitespaces)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.checkBoxShowErrors = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxShowErrors.setText("")
        self.checkBoxShowErrors.setObjectName("checkBoxShowErrors")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBoxShowErrors)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.spinBoxEditorTabLen = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxEditorTabLen.setMaximum(99)
        self.spinBoxEditorTabLen.setProperty("value", 4)
        self.spinBoxEditorTabLen.setObjectName("spinBoxEditorTabLen")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxEditorTabLen)
        self.checkBoxEditorAutoIndent = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxEditorAutoIndent.setChecked(True)
        self.checkBoxEditorAutoIndent.setObjectName("checkBoxEditorAutoIndent")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBoxEditorAutoIndent)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.checkBoxSmartBackspace = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxSmartBackspace.setObjectName("checkBoxSmartBackspace")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBoxSmartBackspace)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBoxEditorCCTriggerLen = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxEditorCCTriggerLen.setProperty("value", 1)
        self.spinBoxEditorCCTriggerLen.setObjectName("spinBoxEditorCCTriggerLen")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxEditorCCTriggerLen)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbLowerCaseKwds = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbLowerCaseKwds.setObjectName("rbLowerCaseKwds")
        self.horizontalLayout.addWidget(self.rbLowerCaseKwds)
        self.rbUpperCaseKwds = QtWidgets.QRadioButton(self.groupBox_4)
        self.rbUpperCaseKwds.setChecked(True)
        self.rbUpperCaseKwds.setObjectName("rbUpperCaseKwds")
        self.horizontalLayout.addWidget(self.rbUpperCaseKwds)
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.comboCcFilterMode = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCcFilterMode.sizePolicy().hasHeightForWidth())
        self.comboCcFilterMode.setSizePolicy(sizePolicy)
        self.comboCcFilterMode.setMinimumSize(QtCore.QSize(134, 0))
        self.comboCcFilterMode.setObjectName("comboCcFilterMode")
        self.comboCcFilterMode.addItem("")
        self.comboCcFilterMode.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboCcFilterMode)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayout_11 = QtWidgets.QFormLayout(self.groupBox_10)
        self.formLayout_11.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_30 = QtWidgets.QLabel(self.groupBox_10)
        self.label_30.setObjectName("label_30")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.comboBoxPreferredEOL = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBoxPreferredEOL.setObjectName("comboBoxPreferredEOL")
        self.comboBoxPreferredEOL.addItem("")
        self.comboBoxPreferredEOL.addItem("")
        self.comboBoxPreferredEOL.addItem("")
        self.comboBoxPreferredEOL.addItem("")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxPreferredEOL)
        self.checkBoxAutodetectEOL = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBoxAutodetectEOL.setChecked(True)
        self.checkBoxAutodetectEOL.setObjectName("checkBoxAutodetectEOL")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxAutodetectEOL)
        self.verticalLayout_7.addWidget(self.groupBox_10)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEditCommentIndicator = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.lineEditCommentIndicator.setFont(font)
        self.lineEditCommentIndicator.setObjectName("lineEditCommentIndicator")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditCommentIndicator)
        self.verticalLayout_7.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ide-icons/rc/cobol-mimetype.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabEditor, icon, "")
        self.tabStyle = QtWidgets.QWidget()
        self.tabStyle.setObjectName("tabStyle")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabStyle)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabStyle)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 641, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.radioButtonColorWhite = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButtonColorWhite.setChecked(True)
        self.radioButtonColorWhite.setObjectName("radioButtonColorWhite")
        self.horizontalLayout_3.addWidget(self.radioButtonColorWhite)
        self.radioButtonColorDark = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButtonColorDark.setObjectName("radioButtonColorDark")
        self.horizontalLayout_3.addWidget(self.radioButtonColorDark)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.layoutIconTheme = QtWidgets.QFormLayout()
        self.layoutIconTheme.setContentsMargins(-1, 0, -1, -1)
        self.layoutIconTheme.setObjectName("layoutIconTheme")
        self.lblIconTheme = QtWidgets.QLabel(self.groupBox_5)
        self.lblIconTheme.setObjectName("lblIconTheme")
        self.layoutIconTheme.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblIconTheme)
        self.comboBoxIconTheme = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBoxIconTheme.setObjectName("comboBoxIconTheme")
        self.layoutIconTheme.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxIconTheme)
        self.verticalLayout_2.addLayout(self.layoutIconTheme)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBox_6)
        self.fontComboBox.setFontFilters(QtWidgets.QFontComboBox.MonospacedFonts)
        font = QtGui.QFont()
        font.setFamily("Clean")
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.horizontalLayout_4.addWidget(self.fontComboBox)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.spinBoxFontSize = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBoxFontSize.setProperty("value", 10)
        self.spinBoxFontSize.setObjectName("spinBoxFontSize")
        self.horizontalLayout_5.addWidget(self.spinBoxFontSize)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidgetColorSchemes = QtWidgets.QListWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetColorSchemes.sizePolicy().hasHeightForWidth())
        self.listWidgetColorSchemes.setSizePolicy(sizePolicy)
        self.listWidgetColorSchemes.setObjectName("listWidgetColorSchemes")
        self.gridLayout_4.addWidget(self.listWidgetColorSchemes, 0, 0, 1, 1)
        self.plainTextEdit = CobolCodeEdit(self.groupBox_7)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 0, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_7)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        icon = QtGui.QIcon.fromTheme("applications-graphics")
        self.tabWidget.addTab(self.tabStyle, icon, "")
        self.tabCompiler = QtWidgets.QWidget()
        self.tabCompiler.setObjectName("tabCompiler")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tabCompiler)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tabCompiler)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 641, 589))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.formLayout_6 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_7)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_8.setObjectName("label_8")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBoxStandard = QtWidgets.QComboBox(self.scrollAreaWidgetContents_7)
        self.comboBoxStandard.setObjectName("comboBoxStandard")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.comboBoxStandard.addItem("")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxStandard)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.checkBoxFreeFormat = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBoxFreeFormat.setText("")
        self.checkBoxFreeFormat.setObjectName("checkBoxFreeFormat")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxFreeFormat)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.cb_static = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_static.setObjectName("cb_static")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_static)
        self.cb_g = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_g.setObjectName("cb_g")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cb_g)
        self.cb_ftrace = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_ftrace.setObjectName("cb_ftrace")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cb_ftrace)
        self.cb_ftraceall = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_ftraceall.setObjectName("cb_ftraceall")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cb_ftraceall)
        self.cb_debugging_line = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.cb_debugging_line.setObjectName("cb_debugging_line")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cb_debugging_line)
        self.le_compiler_flags = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        self.le_compiler_flags.setObjectName("le_compiler_flags")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.le_compiler_flags)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.listWidgetLibPaths = QtWidgets.QListWidget(self.scrollAreaWidgetContents_7)
        self.listWidgetLibPaths.setObjectName("listWidgetLibPaths")
        self.horizontalLayout_10.addWidget(self.listWidgetLibPaths)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolButtonAddLibPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ide-icons/rc/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAddLibPath.setIcon(icon1)
        self.toolButtonAddLibPath.setObjectName("toolButtonAddLibPath")
        self.verticalLayout_4.addWidget(self.toolButtonAddLibPath)
        self.toolButtonRemoveLibPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ide-icons/rc/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonRemoveLibPath.setIcon(icon2)
        self.toolButtonRemoveLibPath.setObjectName("toolButtonRemoveLibPath")
        self.verticalLayout_4.addWidget(self.toolButtonRemoveLibPath)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.formLayout_6.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEditLibs = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEditLibs.setObjectName("lineEditLibs")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEditLibs)
        self.label_compiler_path = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_compiler_path.setObjectName("label_compiler_path")
        self.formLayout_6.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_compiler_path)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEditCompilerPath = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEditCompilerPath.setObjectName("lineEditCompilerPath")
        self.horizontalLayout_9.addWidget(self.lineEditCompilerPath)
        self.toolButtonCustomCompilerPath = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        self.toolButtonCustomCompilerPath.setObjectName("toolButtonCustomCompilerPath")
        self.horizontalLayout_9.addWidget(self.toolButtonCustomCompilerPath)
        self.formLayout_6.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.labelVCVARS = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.labelVCVARS.setObjectName("labelVCVARS")
        self.formLayout_6.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.labelVCVARS)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEditVCVARS = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        self.lineEditVCVARS.setObjectName("lineEditVCVARS")
        self.horizontalLayout_8.addWidget(self.lineEditVCVARS)
        self.toolButtonVCVARS = QtWidgets.QToolButton(self.scrollAreaWidgetContents_7)
        self.toolButtonVCVARS.setObjectName("toolButtonVCVARS")
        self.horizontalLayout_8.addWidget(self.toolButtonVCVARS)
        self.formLayout_6.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_11.addWidget(self.scrollArea_5)
        icon = QtGui.QIcon.fromTheme("exec")
        self.tabWidget.addTab(self.tabCompiler, icon, "")
        self.tabRun = QtWidgets.QWidget()
        self.tabRun.setObjectName("tabRun")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabRun)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tabRun)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 641, 589))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.formLayout_5 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.checkBoxRunExtTerm = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBoxRunExtTerm.setText("")
        self.checkBoxRunExtTerm.setObjectName("checkBoxRunExtTerm")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBoxRunExtTerm)
        self.lineEditRunTerm = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.lineEditRunTerm.setObjectName("lineEditRunTerm")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditRunTerm)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_10.addWidget(self.scrollArea_4)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.tabWidget.addTab(self.tabRun, icon, "")
        self.tabSqlCobol = QtWidgets.QWidget()
        self.tabSqlCobol.setObjectName("tabSqlCobol")
        self.gridLayout = QtWidgets.QGridLayout(self.tabSqlCobol)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tabSqlCobol)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 641, 566))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidgetSQL = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents_5)
        self.stackedWidgetSQL.setObjectName("stackedWidgetSQL")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setObjectName("label_19")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditDbpre = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditDbpre.setObjectName("lineEditDbpre")
        self.horizontalLayout_2.addWidget(self.lineEditDbpre)
        self.toolButtonDbpre = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButtonDbpre.setObjectName("toolButtonDbpre")
        self.horizontalLayout_2.addWidget(self.toolButtonDbpre)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.labelDbpreVersion = QtWidgets.QLabel(self.groupBox_8)
        self.labelDbpreVersion.setStyleSheet("font: oblique 9pt \"Cantarell\";")
        self.labelDbpreVersion.setObjectName("labelDbpreVersion")
        self.verticalLayout_5.addWidget(self.labelDbpreVersion)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_5)
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditCobmysqlapi = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditCobmysqlapi.setObjectName("lineEditCobmysqlapi")
        self.horizontalLayout_6.addWidget(self.lineEditCobmysqlapi)
        self.toolButtonCobMySqlApiPath = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButtonCobMySqlApiPath.setObjectName("toolButtonCobMySqlApiPath")
        self.horizontalLayout_6.addWidget(self.toolButtonCobMySqlApiPath)
        self.formLayout_8.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setObjectName("label_21")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditDbpreFramework = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditDbpreFramework.setObjectName("lineEditDbpreFramework")
        self.horizontalLayout_7.addWidget(self.lineEditDbpreFramework)
        self.toolButtonDbpreFramework = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButtonDbpreFramework.setObjectName("toolButtonDbpreFramework")
        self.horizontalLayout_7.addWidget(self.toolButtonDbpreFramework)
        self.formLayout_8.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.gridLayout_3.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.page)
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.groupBox_9)
        self.formLayout_9.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_22 = QtWidgets.QLabel(self.groupBox_9)
        self.label_22.setObjectName("label_22")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.lineEditDBHOST = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBHOST.setText("")
        self.lineEditDBHOST.setObjectName("lineEditDBHOST")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditDBHOST)
        self.label_23 = QtWidgets.QLabel(self.groupBox_9)
        self.label_23.setObjectName("label_23")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lineEditDBUSER = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBUSER.setObjectName("lineEditDBUSER")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditDBUSER)
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setObjectName("label_24")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEditDBPASSWD = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBPASSWD.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditDBPASSWD.setObjectName("lineEditDBPASSWD")
        self.verticalLayout_6.addWidget(self.lineEditDBPASSWD)
        self.checkBoxShowDbPass = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBoxShowDbPass.setObjectName("checkBoxShowDbPass")
        self.verticalLayout_6.addWidget(self.checkBoxShowDbPass)
        self.formLayout_9.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6)
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEditDBNAME = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBNAME.setText("")
        self.lineEditDBNAME.setObjectName("lineEditDBNAME")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditDBNAME)
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setObjectName("label_26")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEditDBPORT = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBPORT.setText("")
        self.lineEditDBPORT.setObjectName("lineEditDBPORT")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditDBPORT)
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setObjectName("label_27")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lineEditDBSOCKET = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditDBSOCKET.setText("")
        self.lineEditDBSOCKET.setObjectName("lineEditDBSOCKET")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditDBSOCKET)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_9.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.gridLayout_3.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.stackedWidgetSQL.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.formLayout_10 = QtWidgets.QFormLayout(self.page_2)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_29 = QtWidgets.QLabel(self.page_2)
        self.label_29.setObjectName("label_29")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEditESQLOC = QtWidgets.QLineEdit(self.page_2)
        self.lineEditESQLOC.setObjectName("lineEditESQLOC")
        self.horizontalLayout_11.addWidget(self.lineEditESQLOC)
        self.toolButtonESQLOC = QtWidgets.QToolButton(self.page_2)
        self.toolButtonESQLOC.setObjectName("toolButtonESQLOC")
        self.horizontalLayout_11.addWidget(self.toolButtonESQLOC)
        self.formLayout_10.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.stackedWidgetSQL.addWidget(self.page_2)
        self.verticalLayout_9.addWidget(self.stackedWidgetSQL)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout.addWidget(self.scrollArea_3, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tabSqlCobol)
        self.label_28.setOpenExternalLinks(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ide-icons/rc/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabSqlCobol, icon3, "")
        self.widget_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidgetSQL.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.widget.setAccessibleName(_translate("Dialog", "widget", "widget"))
        self.groupBox_3.setTitle(_translate("Dialog", "View"))
        self.label_10.setText(_translate("Dialog", "Display line numbers:"))
        self.checkBoxViewLineNumber.setToolTip(_translate("Dialog", "Show/Hide line numbers"))
        self.checkBoxViewLineNumber.setStatusTip(_translate("Dialog", "Show/Hide line numbers"))
        self.label_11.setText(_translate("Dialog", "Highlight current line:"))
        self.checkBoxHighlightCurrentLine.setToolTip(_translate("Dialog", "Highlight caret line"))
        self.checkBoxHighlightCurrentLine.setStatusTip(_translate("Dialog", "Highlight caret line"))
        self.label_12.setText(_translate("Dialog", "Highlight whitespaces:"))
        self.checkBoxHighlightWhitespaces.setToolTip(_translate("Dialog", "Show visual whitespaces"))
        self.checkBoxHighlightWhitespaces.setStatusTip(_translate("Dialog", "Show visual whitespaces"))
        self.label_13.setText(_translate("Dialog", "Show errors:"))
        self.checkBoxShowErrors.setToolTip(_translate("Dialog", "Compile your code on the fly and show errors while you\'re typing"))
        self.groupBox_2.setTitle(_translate("Dialog", "Indentation"))
        self.label.setText(_translate("Dialog", "Width:"))
        self.spinBoxEditorTabLen.setToolTip(_translate("Dialog", "Tab length (number of spaces)"))
        self.spinBoxEditorTabLen.setStatusTip(_translate("Dialog", "Tab length (number of spaces)"))
        self.checkBoxEditorAutoIndent.setToolTip(_translate("Dialog", "Enable/Disable automatic indentation"))
        self.checkBoxEditorAutoIndent.setStatusTip(_translate("Dialog", "Enable/Disable automatic indentation"))
        self.checkBoxEditorAutoIndent.setText(_translate("Dialog", "Automatic indentation"))
        self.checkBoxSmartBackspace.setToolTip(_translate("Dialog", "Backspace will act as shift+tab, i.e. it will eat as much spaces \n"
"as possible to get back to the previous indentation level."))
        self.checkBoxSmartBackspace.setText(_translate("Dialog", "Intelligent backspace"))
        self.groupBox_4.setTitle(_translate("Dialog", "Code completion"))
        self.label_2.setText(_translate("Dialog", "Trigger length:"))
        self.spinBoxEditorCCTriggerLen.setToolTip(_translate("Dialog", "Number of characters needed to trigger auto completion"))
        self.spinBoxEditorCCTriggerLen.setStatusTip(_translate("Dialog", "Number of characters needed to trigger auto completion"))
        self.label_16.setText(_translate("Dialog", "Proposed keywords:"))
        self.rbLowerCaseKwds.setToolTip(_translate("Dialog", "All proposed keywords are lower-case"))
        self.rbLowerCaseKwds.setText(_translate("Dialog", "&lower-case"))
        self.rbUpperCaseKwds.setToolTip(_translate("Dialog", "All proposed keywords are UPPER-CASE"))
        self.rbUpperCaseKwds.setText(_translate("Dialog", "&UPPER-CASE"))
        self.label_31.setText(_translate("Dialog", "Filter mode:"))
        self.comboCcFilterMode.setItemText(0, _translate("Dialog", "Prefix (faster)"))
        self.comboCcFilterMode.setItemText(1, _translate("Dialog", "Subsequence (smarter)"))
        self.groupBox_10.setTitle(_translate("Dialog", "EOL"))
        self.label_30.setText(_translate("Dialog", "Preferred EOL:"))
        self.comboBoxPreferredEOL.setItemText(0, _translate("Dialog", "System"))
        self.comboBoxPreferredEOL.setItemText(1, _translate("Dialog", "Linux"))
        self.comboBoxPreferredEOL.setItemText(2, _translate("Dialog", "Mac"))
        self.comboBoxPreferredEOL.setItemText(3, _translate("Dialog", "Windows"))
        self.checkBoxAutodetectEOL.setText(_translate("Dialog", "Auto detect EOL"))
        self.groupBox.setTitle(_translate("Dialog", "Comments"))
        self.label_7.setText(_translate("Dialog", "Symbol"))
        self.lineEditCommentIndicator.setText(_translate("Dialog", "*>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEditor), _translate("Dialog", "Editor"))
        self.groupBox_5.setTitle(_translate("Dialog", "Application style"))
        self.radioButtonColorWhite.setToolTip(_translate("Dialog", "Use native style"))
        self.radioButtonColorWhite.setStatusTip(_translate("Dialog", "Use native style"))
        self.radioButtonColorWhite.setText(_translate("Dialog", "Nati&ve"))
        self.radioButtonColorDark.setToolTip(_translate("Dialog", "Use a global dark style (using QDarkStyleSheet)"))
        self.radioButtonColorDark.setStatusTip(_translate("Dialog", "Use a global dark style (using QDarkStyleSheet)"))
        self.radioButtonColorDark.setText(_translate("Dialog", "Dark"))
        self.lblIconTheme.setText(_translate("Dialog", "Icon theme:"))
        self.groupBox_6.setTitle(_translate("Dialog", "Editor font"))
        self.label_3.setText(_translate("Dialog", "Editor font:"))
        self.fontComboBox.setToolTip(_translate("Dialog", "Change editor font"))
        self.fontComboBox.setStatusTip(_translate("Dialog", "Change editor font"))
        self.label_4.setText(_translate("Dialog", "Font size:"))
        self.spinBoxFontSize.setToolTip(_translate("Dialog", "Change editor font size"))
        self.spinBoxFontSize.setStatusTip(_translate("Dialog", "Change editor font size"))
        self.groupBox_7.setTitle(_translate("Dialog", "Editor color scheme"))
        self.listWidgetColorSchemes.setToolTip(_translate("Dialog", "Pygments color schemes."))
        self.listWidgetColorSchemes.setStatusTip(_translate("Dialog", "Pygments color schemes."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStyle), _translate("Dialog", "Style"))
        self.label_8.setText(_translate("Dialog", "Standard:"))
        self.comboBoxStandard.setItemText(0, _translate("Dialog", "default"))
        self.comboBoxStandard.setItemText(1, _translate("Dialog", "cobol2002"))
        self.comboBoxStandard.setItemText(2, _translate("Dialog", "cobol85"))
        self.comboBoxStandard.setItemText(3, _translate("Dialog", "ibm"))
        self.comboBoxStandard.setItemText(4, _translate("Dialog", "mvs"))
        self.comboBoxStandard.setItemText(5, _translate("Dialog", "bs2000"))
        self.comboBoxStandard.setItemText(6, _translate("Dialog", "mf"))
        self.label_9.setText(_translate("Dialog", "Free format:"))
        self.checkBoxFreeFormat.setToolTip(_translate("Dialog", "Code and compile with free format support"))
        self.label_15.setText(_translate("Dialog", "C compiler flags:"))
        self.cb_static.setToolTip(_translate("Dialog", "Link statically"))
        self.cb_static.setText(_translate("Dialog", "-static"))
        self.cb_g.setToolTip(_translate("Dialog", "Enable C compiler debug / stack check / trace"))
        self.cb_g.setText(_translate("Dialog", "-g"))
        self.cb_ftrace.setToolTip(_translate("Dialog", "<html><head/><body><p>Generate trace code</p><p>   - Executed SECTION/PARAGRAPH</p></body></html>"))
        self.cb_ftrace.setText(_translate("Dialog", "-ftrace"))
        self.cb_ftraceall.setToolTip(_translate("Dialog", "<html><head/><body><p>Generate trace code</p><p>  - Executed SECTION/PARAGRAPH/STATEMENTS</p><p>  - Turned on by -debug</p></body></html>"))
        self.cb_ftraceall.setText(_translate("Dialog", "-ftraceall"))
        self.cb_debugging_line.setToolTip(_translate("Dialog", "<html><head/><body><p>Enable debugging lines</p><p>  - \'D\' in indicator column or floating &gt;&gt;D</p></body></html>"))
        self.cb_debugging_line.setText(_translate("Dialog", "-fdebugging-line"))
        self.le_compiler_flags.setToolTip(_translate("Dialog", "You can add other compiler flags here"))
        self.label_17.setText(_translate("Dialog", "Library path:"))
        self.toolButtonAddLibPath.setText(_translate("Dialog", "..."))
        self.toolButtonRemoveLibPath.setText(_translate("Dialog", "..."))
        self.label_18.setText(_translate("Dialog", "Libraries"))
        self.lineEditLibs.setToolTip(_translate("Dialog", "<html><head/><body><p>Add the libraries you would like your programs to link with here (-l option)</p></body></html>"))
        self.label_compiler_path.setText(_translate("Dialog", "Custom compiler:"))
        self.lineEditCompilerPath.setToolTip(_translate("Dialog", "<html><head/><body><p>Custom OpenCobol installation directory. Leave it empty to use the default compiler.</p><p><br/></p><p>Note that this require a restart of the application for the change to be applied.</p></body></html>"))
        self.lineEditCompilerPath.setStatusTip(_translate("Dialog", "Custom OpenCobol installation directory"))
        self.toolButtonCustomCompilerPath.setText(_translate("Dialog", "..."))
        self.labelVCVARS.setText(_translate("Dialog", "VCVARS32 path:"))
        self.lineEditVCVARS.setToolTip(_translate("Dialog", "<html><head/><body><p>Path to VCVARS32.bat. VCVARS32.bat is needed if you\'re using a GnuCobol compiler built with Visual Studio.</p><p><br/></p><p>The VCVARS32.bat file is located under the bin directory of you Visual C++ installation. Make sure to use the same version as the one used to build the compiler!</p></body></html>"))
        self.toolButtonVCVARS.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCompiler), _translate("Dialog", "Compiler"))
        self.label_5.setText(_translate("Dialog", "Run in external terminal:"))
        self.checkBoxRunExtTerm.setToolTip(_translate("Dialog", "Enable/Disable running program in an external terminal"))
        self.checkBoxRunExtTerm.setStatusTip(_translate("Dialog", "Enable/Disable running program in an external terminal"))
        self.lineEditRunTerm.setToolTip(_translate("Dialog", "External terminal command (filename is appended at the end of the command)"))
        self.lineEditRunTerm.setStatusTip(_translate("Dialog", "External terminal command"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRun), _translate("Dialog", "Run"))
        self.groupBox_8.setTitle(_translate("Dialog", "DBPRE Configuration"))
        self.label_19.setText(_translate("Dialog", "dbpre"))
        self.toolButtonDbpre.setText(_translate("Dialog", "..."))
        self.labelDbpreVersion.setText(_translate("Dialog", "invalid dbpre executable"))
        self.label_20.setText(_translate("Dialog", "cobmysqlapi:"))
        self.toolButtonCobMySqlApiPath.setText(_translate("Dialog", "..."))
        self.label_21.setText(_translate("Dialog", "Framework:"))
        self.toolButtonDbpreFramework.setText(_translate("Dialog", "..."))
        self.groupBox_9.setTitle(_translate("Dialog", "DB Connection Parameters"))
        self.label_22.setText(_translate("Dialog", "DBHOST:"))
        self.label_23.setText(_translate("Dialog", "DBUSER:"))
        self.label_24.setText(_translate("Dialog", "DBPASSWD:"))
        self.checkBoxShowDbPass.setText(_translate("Dialog", "Show password"))
        self.label_25.setText(_translate("Dialog", "DBNAME:"))
        self.label_26.setText(_translate("Dialog", "DBPORT:"))
        self.label_27.setText(_translate("Dialog", "DBSOCKET:"))
        self.label_29.setText(_translate("Dialog", "esqlOC folder:"))
        self.toolButtonESQLOC.setText(_translate("Dialog", "..."))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Read the <a href=\"http://opencobolide.readthedocs.org/en/latest/advanced.html#how-to-setup-dbpre-integration-with-opencobolide\"><span style=\" text-decoration: underline; color:#2980b9;\">guide</span></a> to get started</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSqlCobol), _translate("Dialog", "SQL Cobol"))

from pyqode.cobol.widgets import CobolCodeEdit
from . import ide_rc