.\" Manpage for OpenCobolIDE.
.\" Contact colin.duquesnoy@gmail.com to correct errors or typos.
.TH man 1 "07 Dec 2013" "2.0.1" "open-cobol-ide man page"
.SH NAME
OpenCobolIDE \- starts the IDE
.SH SYNOPSIS
OpenCobolIDE
.SH DESCRIPTION
A simple and lightweight COBOL IDE based on OpenCOBOL and pyQode.
.SH OPTIONS
OpenCobolIDE does not take any options or arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Colin Duquesnoy (colin.duquesnoy@gmail.com)