.\" Manpage for open-cobol-ide.
.\" Contact colin.duquesnoy@gmail.com to correct errors or typos.
.TH man 1 "07 Dec 2013" "2.0.1" "open-cobol-ide man page"
.SH NAME
open-codol-ide \- starts the IDE
.SH SYNOPSIS
open-cobol-ide
.SH DESCRIPTION
A simple and lightweight COBOL IDE based on OpenCOBOL and pyQode.
.SH OPTIONS
open-cobol-ide does not take any options or arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Colin Duquesnoy (colin.duquesnoy@gmail.com)